/**
 * THEME BLUEPRINT REGISTRY - LUXENARY ENGINE
 * Single Source of Truth for Theme-Scoped Narratives, Quotes & Section Labels.
 * Each theme features tailored cultural/editorial defaults that reflect its unique persona.
 */

export interface ThemeBlueprint {
  themeId: string;
  themeName: string;
  series: "traditional" | "modern" | "premium";
  openingQuote: string;
  openingQuoteRef: string;
  coverSubtitle: string;
  openBtn: string;
  quoteSectionTitle: string;
  quoteSectionEyebrow: string;
  coupleSectionEyebrow?: string;
  coupleSectionTitle: string;
  coupleSectionSub: string;
  eventsSectionTitle: string;
  eventsSectionSub: string;
  storySectionTitle: string;
  storySectionEyebrow?: string;
  gallerySectionTitle: string;
  gallerySectionEyebrow: string;
  galleryQuote: string;
  dressCodeTitle?: string;
  dressCodeEyebrow?: string;
  dressCodeSubtitle?: string;
  streamingTitle?: string;
  streamingEyebrow?: string;
  streamingSubtitle?: string;
  giftSectionTitle: string;
  giftSectionEyebrow: string;
  giftSectionDesc: string;
  turutMengundangTitle?: string;
  turutMengundangEyebrow?: string;
  turutMengundangSubtitle?: string;
  wishesSectionTitle: string;
  wishesSectionSub: string;
  closingQuote: string;
  closingSub: string;
  rsvpTitle: string;
  rsvpBtnText?: string;
}

export const THEME_BLUEPRINTS: Record<string, ThemeBlueprint> = {
  // ── TRADITIONAL HERITAGE SERIES ──
  candani: {
    themeId: "candani",
    themeName: "Candani",
    series: "traditional",
    openingQuote: "Bismillahir Rahmanir Rahim. Narekko purai sikaleng, tessisarakang lino ahera. Dengan memohon ridho dan rahmat Allah SWT, kami bermaksud melangsungkan ikatan suci pernikahan.",
    openingQuoteRef: "PAPPASENG TO RIOLO & QS. AR-RUM: 21",
    coverSubtitle: "Tanpa mengurangi rasa hormat, kami mengundang Bapak/Ibu/Saudara/i untuk menghadiri hari bahagia kami.",
    openBtn: "Buka Undangan",
    quoteSectionTitle: "Pappaseng & Doa",
    quoteSectionEyebrow: "WALIMATUL 'URS",
    coupleSectionTitle: "Dua Insan",
    coupleSectionSub: "Dua Hati Bersatu Menjalin Mappakaraja",
    eventsSectionTitle: "Rangkaian Acara",
    eventsSectionSub: "Waktu & Tempat Pelaksanaan Akad & Resepsi",
    storySectionTitle: "Love Story",
    storySectionEyebrow: "Our Journey",
    gallerySectionTitle: "Our Moments",
    gallerySectionEyebrow: "Gallery",
    galleryQuote: "Cinta sejati adalah ketika dua insan saling memuliakan dalam ketaatan dan keikhlasan.",
    dressCodeTitle: "Dress Code",
    dressCodeEyebrow: "A Guide To",
    dressCodeSubtitle: "Kami mengundang tamu undangan untuk mengenakan palet warna berikut:",
    streamingTitle: "Live Streaming",
    streamingEyebrow: "Virtual Ceremony",
    streamingSubtitle: "Bagi keluarga & sahabat yang menyaksikan dari jauh, bergabunglah melalui siaran daring:",
    giftSectionTitle: "Tanda Kasih",
    giftSectionEyebrow: "Tanda Penghormatan",
    giftSectionDesc: "Doa restu Anda merupakan karunia yang sangat berarti bagi kami. Dan jika memberi adalah ungkapan tanda kasih, Anda dapat mengirimkannya secara digital:",
    turutMengundangTitle: "Turut Mengundang",
    turutMengundangEyebrow: "Keluarga Besar",
    turutMengundangSubtitle: "Keluarga Besar & Kerabat yang turut berbahagia:",
    wishesSectionTitle: "Pappaseng & Doa Restu",
    wishesSectionSub: "Untaian Harapan & Doa Suci Dari Sahabat Serta Kerabat",
    closingQuote: "Merupakan suatu kehormatan dan kebahagiaan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir dan memberikan doa restu.",
    closingSub: "Salam hangat penuh hormat dari keluarga besar kedua mempelai.",
    rsvpTitle: "Konfirmasi Kehadiran & Doa",
    rsvpBtnText: "Kirim Konfirmasi & Doa",
  },
  dillalucky: {
    themeId: "dillalucky",
    themeName: "Dillalucky",
    series: "traditional",
    openingQuote: "Nyuwun donga pangestu dhumateng Gusti Kang Akarya Jagad, mugi tansah paring berkah karaharjan dhumateng gesang kekalih.",
    openingQuoteRef: "SERAT WEDHATAMA & QS. AR-RUM: 21",
    coverSubtitle: "Kanthi asma Gusti Ingkang Maha Asih, kula sakulawarga ngaturaken rawuh panjenengan sedaya.",
    openBtn: "Buka Serat Undangan",
    quoteSectionTitle: "Serat Panyuwunan",
    quoteSectionEyebrow: "PRANATAN DHOHAR",
    coupleSectionTitle: "Temanten Sekar",
    coupleSectionSub: "Nyawiji Ing Tresna Asih Sejati",
    eventsSectionTitle: "Adicara Pawiwahan",
    eventsSectionSub: "Tata Wanci Saha Palenggahan Adicara",
    storySectionTitle: "Lelampahan Katresnan",
    gallerySectionTitle: "Babar Momen",
    gallerySectionEyebrow: "SESAWANGAN",
    galleryQuote: "Tresna sejati ora bakal luntur dening lumakuning mangsa.",
    giftSectionTitle: "Kado Katresnan",
    giftSectionEyebrow: "TANDHA KASIH",
    giftSectionDesc: "Donga pangestu panjenengan dados berkah ingkang tanpa upami. Bilih kepareng paring tandha kasih kanthi digital:",
    wishesSectionTitle: "Atur Bela Sungkawa & Donga",
    wishesSectionSub: "Pangestu Tulus Saking Para Pinisepuh Saha Mitra",
    closingQuote: "Matur nuwun sanget awit saking sih kadarman panjenengan sedaya ingkang sampun kersa rawuh saha paring berkah pangestu.",
    closingSub: "Kula sakulawarga agung ngaturaken gunging panuwun ingkang tanpa pepindhan.",
    rsvpTitle: "Konfirmasi Rawuh & Donga",
  },
  prameswari: {
    themeId: "prameswari",
    themeName: "Prameswari",
    series: "traditional",
    openingQuote: "Dan di antara tanda-tanda kebesaran-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya.",
    openingQuoteRef: "QS. AR-RUM : 21",
    coverSubtitle: "Dengan penuh rasa syukur dan hormat, kami mengundang kehadiran Bapak/Ibu/Sahabat tercinta.",
    openBtn: "Buka Undangan",
    quoteSectionTitle: "Untaian Doa",
    quoteSectionEyebrow: "WALIMATUL 'URS",
    coupleSectionTitle: "Sang Mempelai",
    coupleSectionSub: "Dua Jiwa Bersatu Dalam Ikatan Agung",
    eventsSectionTitle: "Agenda Acara",
    eventsSectionSub: "Waktu & Tempat Pelaksanaan",
    storySectionTitle: "Kisah Kasih",
    gallerySectionTitle: "Momen Sakral",
    gallerySectionEyebrow: "GALERI KENANGAN",
    galleryQuote: "Dua hati yang tertaut dalam ikatan suci pernikahan berpayung ridho Ilahi.",
    giftSectionTitle: "Tanda Kasih",
    giftSectionEyebrow: "UNGKAPAN CINTA",
    giftSectionDesc: "Kehadiran dan doa Anda adalah anugerah terbesar bagi kami. Jika ingin memberikan tanda kasih secara cashless:",
    wishesSectionTitle: "Doa & Restu",
    wishesSectionSub: "Kirimkan Pesan Manis Untuk Mempelai",
    closingQuote: "Tiada yang lebih berharga selain doa tulus dan restu yang Anda curahkan untuk mengawali bahtera rumah tangga kami.",
    closingSub: "Keluarga Besar Kedua Mempelai",
    rsvpTitle: "Konfirmasi Kehadiran",
  },
  mayang: {
    themeId: "mayang",
    themeName: "Mayang",
    series: "traditional",
    openingQuote: "Mugi Gusti nangtayungan, ngahijikeun dua insan dina iketan suci jatukrami nu barokah, sakinah, mawaddah, warahmah.",
    openingQuoteRef: "PANYUWUNAN DO'A & QS. AR-RUM: 21",
    coverSubtitle: "Kalayan nyuhunkeun widi sareng ridho Allah SWT, simkuring sakulawargi ngulem wargi sadaya.",
    openBtn: "Buka Uleman",
    quoteSectionTitle: "Pangbagea & Doa",
    quoteSectionEyebrow: "WALIMATUL 'URSY",
    coupleSectionTitle: "Calon Panganten",
    coupleSectionSub: "Ngaitkeun Janji Satia Dina Asih",
    eventsSectionTitle: "Runtuyan Acara",
    eventsSectionSub: "Waktos Sareng Tempat Lumangsungna Acara",
    storySectionTitle: "Rengkak Rawayan",
    gallerySectionTitle: "Albeum Momen",
    gallerySectionEyebrow: "POTRET DUA INSAN",
    galleryQuote: "Dua rasa nu ngahiji dina hiji niat suci, ngawangun kulawarga bagja salalawasna.",
    giftSectionTitle: "Kintunan Asih",
    giftSectionEyebrow: "TANDA KASIH",
    giftSectionDesc: "Pangdonga ti saderek sadayana mangrupakeun anugrah anu ageung pisan kanggo simkuring:",
    wishesSectionTitle: "Pangwilujeng & Doa",
    wishesSectionSub: "Haturkeun Doa Restu Ti Sahabat Sareng Wargi",
    closingQuote: "Hatur nuhun kana sagala perhatosan, pangdua, sareng kasumpingan saderek sadayana.",
    closingSub: "Hormat simkuring sakulawargi agung.",
    rsvpTitle: "Konfirmasi Kasumpingan",
  },
  badrika: {
    themeId: "badrika",
    themeName: "Badrika",
    series: "traditional",
    openingQuote: "Maha Suci Allah yang telah menciptakan makhluk-Nya berpasang-pasangan. Izinkan kami menyempurnakan separuh agama ini.",
    openingQuoteRef: "QS. AZ-ZARIYAT : 49",
    coverSubtitle: "Tanpa mengurangi rasa hormat, perkenankan kami mengundang Anda untuk merayakan cinta kami.",
    openBtn: "Buka Undangan",
    quoteSectionTitle: "Ayat & Doa Suci",
    quoteSectionEyebrow: "THE SACRED UNION",
    coupleSectionTitle: "Mempelai Berbahagia",
    coupleSectionSub: "Langkah Pertama Menuju Keabadian",
    eventsSectionTitle: "Rangkaian Acara",
    eventsSectionSub: "Waktu & Tempat Pelaksanaan Akad Serta Resepsi",
    storySectionTitle: "Kisah Kasih Kami",
    gallerySectionTitle: "Galeri Foto",
    gallerySectionEyebrow: "POTRET KENANGAN",
    galleryQuote: "Di setiap langkah kami saling menemukan, di setiap doa kami saling menguatkan.",
    giftSectionTitle: "Tanda Kasih",
    giftSectionEyebrow: "WEDDING GIFT",
    giftSectionDesc: "Doa restu Anda merupakan karunia yang sangat berarti bagi kami. Jika berkenan memberi kado digital:",
    wishesSectionTitle: "Ucapan & Doa",
    wishesSectionSub: "Kirimkan Pesan Manis Untuk Mempelai",
    closingQuote: "Kehadiran dan doa restu Anda adalah pelita yang menerangi langkah awal perjalanan hidup kami.",
    closingSub: "Keluarga Besar Mempelai",
    rsvpTitle: "Konfirmasi Kehadiran & Doa",
  },

  // ── MODERN EDITORIAL SERIES ──
  ameera: {
    themeId: "ameera",
    themeName: "Ameera",
    series: "modern",
    openingQuote: "In all the world, there is no heart for me like yours. In all the world, there is no love for you like mine.",
    openingQuoteRef: "MAYA ANGELOU",
    coverSubtitle: "We warmly invite you to celebrate our union and witness the beginning of our forever.",
    openBtn: "Open Invitation",
    quoteSectionTitle: "Words of Love",
    quoteSectionEyebrow: "THE SACRED VOWS",
    coupleSectionTitle: "The Couple",
    coupleSectionSub: "Two paths, one destination: forever together.",
    eventsSectionTitle: "The Celebration",
    eventsSectionSub: "Save the Date & Location",
    storySectionTitle: "Our Love Story",
    gallerySectionTitle: "Captured Moments",
    gallerySectionEyebrow: "THE GALLERY",
    galleryQuote: "Every love story is beautiful, but ours is our absolute favorite.",
    giftSectionTitle: "Wedding Gift",
    giftSectionEyebrow: "TOKEN OF LOVE",
    giftSectionDesc: "Your presence at our wedding is the greatest gift of all. However, should you wish to honor us with a gift, a cashless gesture is warmly welcomed:",
    wishesSectionTitle: "Wishes & Prayers",
    wishesSectionSub: "Leave a Warm Message for the Couple",
    closingQuote: "Thank you for being part of our story and celebrating this unforgettable chapter with us.",
    closingSub: "With love and gratitude, the happy couple & families.",
    rsvpTitle: "RSVP & Best Wishes",
  },
  chronicle: {
    themeId: "chronicle",
    themeName: "Chronicle",
    series: "modern",
    openingQuote: "And suddenly all the love songs were about you. Here begins the greatest adventure of our lives.",
    openingQuoteRef: "THE LOVE CHRONICLES",
    coverSubtitle: "An exclusive invitation to witness and celebrate the union of two hearts.",
    openBtn: "Read Invitation",
    quoteSectionTitle: "The Prologue",
    quoteSectionEyebrow: "CHAPTER ZERO",
    coupleSectionTitle: "The Protagonists",
    coupleSectionSub: "Where love found its true rhythm.",
    eventsSectionTitle: "The Schedule",
    eventsSectionSub: "Details of Holy Matrimony & Reception",
    storySectionTitle: "Chapters of Us",
    gallerySectionTitle: "Visual Chronicle",
    gallerySectionEyebrow: "PHOTO ESSAY",
    galleryQuote: "Captured in time, framed by love, cherished forever.",
    giftSectionTitle: "Wedding Registry",
    giftSectionEyebrow: "TOKEN OF APPRECIATION",
    giftSectionDesc: "Your prayers are our greatest treasure. For those wishing to send a digital wedding gift:",
    wishesSectionTitle: "Guest Messages",
    wishesSectionSub: "Share Your Warmest Blessings",
    closingQuote: "The best chapter is the one we write together with everyone we cherish.",
    closingSub: "Warmest regards from both families.",
    rsvpTitle: "RSVP & Guestbook",
  },
  lumina: {
    themeId: "lumina",
    themeName: "Lumina",
    series: "modern",
    openingQuote: "Love does not consist in gazing at each other, but in looking outward together in the same direction.",
    openingQuoteRef: "ANTOINE DE SAINT-EXUPÉRY",
    coverSubtitle: "Together with our families, we joyfully invite you to our wedding celebration.",
    openBtn: "Explore Invitation",
    quoteSectionTitle: "Reflection",
    quoteSectionEyebrow: "A GLIMPSE OF ETERNITY",
    coupleSectionTitle: "The Bride & Groom",
    coupleSectionSub: "Illuminated by love, blessed with faith.",
    eventsSectionTitle: "The Gathering",
    eventsSectionSub: "Ceremony & Celebration Details",
    storySectionTitle: "How It Began",
    gallerySectionTitle: "Moments of Light",
    gallerySectionEyebrow: "EXQUISITE GALLERY",
    galleryQuote: "In the gentle warmth of love, everything finds its meaning.",
    giftSectionTitle: "Wedding Gift",
    giftSectionEyebrow: "SEND LOVE",
    giftSectionDesc: "Your blessings mean the world to us. Should you wish to send a token of love electronically:",
    wishesSectionTitle: "Warm Wishes",
    wishesSectionSub: "Send Love and Prayers for Our Journey",
    closingQuote: "Your presence and sincere prayers will complete the radiance of our joyous celebration.",
    closingSub: "With endless gratitude, from both families.",
    rsvpTitle: "RSVP & Confirmation",
  },
  papercut: {
    themeId: "papercut",
    themeName: "Papercut",
    series: "modern",
    openingQuote: "Setiap helai kisah yang kita rajut bermuara pada satu janji: setia mengarungi hidup bersama hingga usia senja.",
    openingQuoteRef: "UNTUK SELAMANYA",
    coverSubtitle: "Kisah cinta kami terukir indah, dan kami ingin membagikan kebahagiaan ini bersama Anda.",
    openBtn: "Buka Undangan",
    quoteSectionTitle: "Rajutan Kisah",
    quoteSectionEyebrow: "JANJI SETIA",
    coupleSectionTitle: "Dua Mempelai",
    coupleSectionSub: "Dipersatukan oleh takdir, diteguhkan oleh cinta.",
    eventsSectionTitle: "Agenda Acara",
    eventsSectionSub: "Waktu & Lokasi Penyelenggaraan",
    storySectionTitle: "Alur Waktu",
    gallerySectionTitle: "Potret Momen",
    gallerySectionEyebrow: "GALERI CINTA",
    galleryQuote: "Keindahan cinta terpancar dari kebersamaan yang tulus dan bersahaja.",
    giftSectionTitle: "Tanda Kasih",
    giftSectionEyebrow: "KADO PERNIKAHAN",
    giftSectionDesc: "Doa restu Anda adalah karunia terindah. Jika berkenan memberikan tanda kasih secara digital:",
    wishesSectionTitle: "Ungkapan Doa",
    wishesSectionSub: "Tuliskan Ucapan & Doa Tulus Anda",
    closingQuote: "Terima kasih atas segala doa, tawa, dan kebersamaan yang senantiasa menemani perjalanan kami.",
    closingSub: "Salam hangat penuh cinta dari kami berdua.",
    rsvpTitle: "Konfirmasi Kehadiran",
  },
  solaria: {
    themeId: "solaria",
    themeName: "Solaria",
    series: "modern",
    openingQuote: "Wherever you go, I will go; and wherever you lodge, I will lodge. Your journey is my journey, forever.",
    openingQuoteRef: "PROMISE OF HORIZON",
    coverSubtitle: "Under the warm golden glow of dusk, we invite you to share our happiest moment.",
    openBtn: "Step Inside",
    quoteSectionTitle: "Golden Vows",
    quoteSectionEyebrow: "THE HORIZON",
    coupleSectionTitle: "The Couple",
    coupleSectionSub: "Under one sky, stepping into infinity.",
    eventsSectionTitle: "The Events",
    eventsSectionSub: "Time & Venue of Our Wedding Day",
    storySectionTitle: "The Journey",
    gallerySectionTitle: "Sunlit Memories",
    gallerySectionEyebrow: "PHOTO SHOWCASE",
    galleryQuote: "True love shines through every season, constant and unwavering.",
    giftSectionTitle: "Wedding Gift",
    giftSectionEyebrow: "SHARED LOVE",
    giftSectionDesc: "Having you celebrate with us is the greatest honor. If you wish to send a cashless gift:",
    wishesSectionTitle: "Guest Messages",
    wishesSectionSub: "Write a Note of Celebration",
    closingQuote: "Thank you for gracing our special day with your warmth, love, and blessing.",
    closingSub: "Love and light always from our families.",
    rsvpTitle: "RSVP & Greetings",
  },
  wave: {
    themeId: "wave",
    themeName: "Wave",
    series: "modern",
    openingQuote: "Like ocean waves returning to the shore, true love always finds its way home.",
    openingQuoteRef: "OCEAN OF DEVOTION",
    coverSubtitle: "Please join us as we celebrate our new beginning on this momentous day.",
    openBtn: "Open Invitation",
    quoteSectionTitle: "Currents of Love",
    quoteSectionEyebrow: "THE RHYTHM",
    coupleSectionTitle: "The Couple",
    coupleSectionSub: "Flowing together in harmony, boundless and true.",
    eventsSectionTitle: "Wedding Schedule",
    eventsSectionSub: "When & Where We Tie the Knot",
    storySectionTitle: "Tides of Time",
    gallerySectionTitle: "Gallery of Memories",
    gallerySectionEyebrow: "TIMELESS MOMENTS",
    galleryQuote: "Love is the anchor that holds our hearts through every tide.",
    giftSectionTitle: "Gift & Registry",
    giftSectionEyebrow: "TOKEN OF BLESSING",
    giftSectionDesc: "Your presence is our present. Should you wish to bless us with a cashless wedding gift:",
    wishesSectionTitle: "Wishes & Warmth",
    wishesSectionSub: "Send Your Best Prayers for the Couple",
    closingQuote: "Your blessing is the sweetest gentle tide carrying us into our new journey.",
    closingSub: "Warmest regards from both families.",
    rsvpTitle: "RSVP & Confirmation",
  },

  // ── PREMIUM EXCLUSIVE SERIES ──
  artisan: {
    themeId: "artisan",
    themeName: "Artisan",
    series: "premium",
    openingQuote: "True art is love made visible. We are profoundly honored to share this sacred milestone with you.",
    openingQuoteRef: "THE ARTISAN VOWS",
    coverSubtitle: "Together with our esteemed families, we request the honor of your gracious presence.",
    openBtn: "Enter Celebration",
    quoteSectionTitle: "The Heritage",
    quoteSectionEyebrow: "MASTERPIECE OF HEARTS",
    coupleSectionTitle: "The Couple",
    coupleSectionSub: "Handcrafted love, timeless elegance.",
    eventsSectionTitle: "The Solemnity",
    eventsSectionSub: "Ceremony & Reception Program",
    storySectionTitle: "The Tapestry",
    gallerySectionTitle: "The Exhibition",
    gallerySectionEyebrow: "CURATED FRAMES",
    galleryQuote: "A masterwork composed of love, trust, and perpetual devotion.",
    giftSectionTitle: "Wedding Registry",
    giftSectionEyebrow: "TOKEN OF RESPECT",
    giftSectionDesc: "Your prayers are the finest tribute to our new beginning. For digital wedding gifts:",
    wishesSectionTitle: "Expressions of Grace",
    wishesSectionSub: "Convey Your Heartfelt Prayers & Best Wishes",
    closingQuote: "We extend our deepest gratitude for your blessings and distinguished presence.",
    closingSub: "Respectfully, the bride, the groom & families.",
    rsvpTitle: "RSVP & Attendance",
  },
  aurelia: {
    themeId: "aurelia",
    themeName: "Aurelia",
    series: "premium",
    openingQuote: "Love is golden when crowned with sincerity, reverence, and unconditional devotion.",
    openingQuoteRef: "AURELIA GOLDEN ARCHIVE",
    coverSubtitle: "An exclusive invitation to celebrate the eternal union of two souls.",
    openBtn: "View Invitation",
    quoteSectionTitle: "Golden Devotion",
    quoteSectionEyebrow: "CELEBRATING ETERNITY",
    coupleSectionTitle: "The Bride & Groom",
    coupleSectionSub: "Reflecting grace, bound in sacred unity.",
    eventsSectionTitle: "The Itinerary",
    eventsSectionSub: "Times & Prestigious Venue",
    storySectionTitle: "The Golden Era",
    gallerySectionTitle: "Golden Gallery",
    gallerySectionEyebrow: "TIMELESS BEAUTY",
    galleryQuote: "Where hearts align under golden grace, eternity begins.",
    giftSectionTitle: "Tribute of Love",
    giftSectionEyebrow: "WEDDING GIFT",
    giftSectionDesc: "Your gracious blessings honor us deeply. If you wish to convey a digital tribute:",
    wishesSectionTitle: "Warm Blessings",
    wishesSectionSub: "Inscribe Your Best Wishes for Our Lifetime",
    closingQuote: "Your esteemed presence and heartfelt wishes are our greatest blessing.",
    closingSub: "With heartfelt appreciation and honor.",
    rsvpTitle: "RSVP & Confirmation",
  },
  kalandra: {
    themeId: "kalandra",
    themeName: "Kalandra",
    series: "premium",
    openingQuote: "Dari keheningan menuju keabadian, dua jiwa berikrar membangun singgasana rumah tangga penuh berkah.",
    openingQuoteRef: "UNTUK MASA DEPAN",
    coverSubtitle: "Kehadiran Bapak/Ibu/Saudara/i merupakan kehormatan tak terhingga bagi keluarga besar kami.",
    openBtn: "Buka Undangan",
    quoteSectionTitle: "Janji Luhur",
    quoteSectionEyebrow: "ROYAL SOLEMNIZATION",
    coupleSectionTitle: "Kedua Mempelai",
    coupleSectionSub: "Menapaki Mahligai Cinta Dalam Ridho Illahi",
    eventsSectionTitle: "Rangkaian Acara",
    eventsSectionSub: "Waktu & Tempat Akad Serta Resepsi",
    storySectionTitle: "Lembah Cinta",
    gallerySectionTitle: "Potret Keabadian",
    gallerySectionEyebrow: "GALLERY OF LOVE",
    galleryQuote: "Kala dua takdir dipersatukan, keindahan cinta menjadi nyata selamanya.",
    giftSectionTitle: "Tanda Kasih",
    giftSectionEyebrow: "WEDDING GIFT",
    giftSectionDesc: "Doa restu Anda adalah karunia yang sangat berarti. Bagi yang ingin memberikan tanda kasih secara cashless:",
    wishesSectionTitle: "Ucapan & Doa Restu",
    wishesSectionSub: "Sampaikan Doa Terbaik Anda Untuk Kedua Mempelai",
    closingQuote: "Doa tulus Anda adalah anugerah terindah yang senantiasa menguatkan bahtera rumah tangga kami.",
    closingSub: "Salam hormat dan terima kasih dari kami sekeluarga.",
    rsvpTitle: "Konfirmasi Kehadiran & Doa",
  },
  valente: {
    themeId: "valente",
    themeName: "Valente",
    series: "premium",
    openingQuote: "To love and to be loved is to feel the sun from both sides. We invite you to witness our eternal promise.",
    openingQuoteRef: "DAVID VISCOTT",
    coverSubtitle: "With joyful hearts, we request the pleasure of your company at our wedding.",
    openBtn: "Open Invitation",
    quoteSectionTitle: "The Solemn Vow",
    quoteSectionEyebrow: "FOREVER BOUND",
    coupleSectionTitle: "The Couple",
    coupleSectionSub: "United by destiny, inspired by devotion.",
    eventsSectionTitle: "The Occasion",
    eventsSectionSub: "Order of Service & Reception",
    storySectionTitle: "Milestones",
    gallerySectionTitle: "Curated Moments",
    gallerySectionEyebrow: "EXCLUSIVE FRAMES",
    galleryQuote: "In black and white or vibrant hues, love remains pure and true.",
    giftSectionTitle: "Wedding Registry",
    giftSectionEyebrow: "GRACIOUS TOKEN",
    giftSectionDesc: "Your presence is our supreme delight. For guests desiring to send a cashless gift:",
    wishesSectionTitle: "Words of Blessing",
    wishesSectionSub: "Leave Your Blessing for the Bride & Groom",
    closingQuote: "Our celebration is made truly whole by your presence, love, and prayers.",
    closingSub: "With profound gratitude, the families.",
    rsvpTitle: "RSVP & Attendance",
  },
};

/**
 * Default Category Archetypes for newly added themes
 */
export const DEFAULT_TRADITIONAL_BLUEPRINT: ThemeBlueprint = {
  themeId: "generic_traditional",
  themeName: "Traditional Heritage",
  series: "traditional",
  openingQuote: "Dan di antara tanda-tanda (kebesaran)-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya, dan Dia menjadikan di antaramu rasa kasih dan sayang.",
  openingQuoteRef: "QS. AR-RUM : 21",
  coverSubtitle: "Tanpa mengurangi rasa hormat, kami mengundang Anda untuk menghadiri acara pernikahan kami.",
  openBtn: "Buka Undangan",
  quoteSectionTitle: "Untaian Doa",
  quoteSectionEyebrow: "WALIMATUL 'URS",
  coupleSectionTitle: "Mempelai",
  coupleSectionSub: "Dengan penuh rasa syukur dan sukacita, kami mengundang Anda untuk merayakan persatuan cinta kami.",
  eventsSectionTitle: "Rangkaian Acara",
  eventsSectionSub: "Waktu & Tempat Pelaksanaan",
  storySectionTitle: "Kisah Cinta",
  storySectionEyebrow: "Our Journey",
  gallerySectionTitle: "Galeri Momen",
  gallerySectionEyebrow: "Gallery",
  galleryQuote: "Cinta sejati adalah ketika dua insan saling memuliakan dalam ketaatan dan keikhlasan.",
  dressCodeTitle: "Dress Code",
  dressCodeEyebrow: "A Guide To",
  dressCodeSubtitle: "Kami mengundang tamu undangan untuk mengenakan palet warna berikut:",
  streamingTitle: "Live Streaming",
  streamingEyebrow: "Virtual Ceremony",
  streamingSubtitle: "Bagi keluarga & sahabat yang menyaksikan dari jauh, bergabunglah melalui siaran daring:",
  giftSectionTitle: "Tanda Kasih",
  giftSectionEyebrow: "WEDDING GIFT",
  giftSectionDesc: "Doa restu Anda merupakan karunia yang sangat berarti bagi kami. Dan jika memberi adalah ungkapan tanda kasih Anda, Anda dapat memberi kado secara digital:",
  turutMengundangTitle: "Turut Mengundang",
  turutMengundangEyebrow: "Keluarga Besar",
  turutMengundangSubtitle: "Keluarga Besar & Kerabat yang turut berbahagia:",
  wishesSectionTitle: "Ucapan & Doa Restu",
  wishesSectionSub: "Kirimkan Pesan Manis Untuk Mempelai",
  closingQuote: "Merupakan suatu kehormatan dan kebahagiaan bagi kami apabila Anda berkenan hadir dan memberikan doa restu.",
  closingSub: "Salam hangat dari keluarga besar kedua mempelai.",
  rsvpTitle: "Konfirmasi Kehadiran & Doa",
  rsvpBtnText: "Kirim Konfirmasi & Doa",
};

export const DEFAULT_MODERN_BLUEPRINT: ThemeBlueprint = {
  themeId: "generic_modern",
  themeName: "Modern Minimalist",
  series: "modern",
  openingQuote: "Two souls with but a single thought, two hearts that beat as one. In the presence of God and our beloved families, we unite our lives in love.",
  openingQuoteRef: "CELEBRATION OF LOVE",
  coverSubtitle: "Together with their families, invite you to celebrate the joyous union of their marriage.",
  openBtn: "Open Invitation",
  quoteSectionTitle: "The Union",
  quoteSectionEyebrow: "TWO HEARTS AS ONE",
  coupleSectionTitle: "The Happy Couple",
  coupleSectionSub: "Together with joyful hearts, we invite you to share this sacred beginning with us.",
  eventsSectionTitle: "The Itinerary",
  eventsSectionSub: "Ceremony & Celebration Schedule",
  storySectionTitle: "Love Story",
  storySectionEyebrow: "Our Journey",
  gallerySectionTitle: "Our Moments",
  gallerySectionEyebrow: "Captured Memories",
  galleryQuote: "Every moment together is another piece of our eternal story.",
  dressCodeTitle: "Dress Code",
  dressCodeEyebrow: "Attire Guide",
  dressCodeSubtitle: "We invite our lovely guests to dress in our curated palette:",
  streamingTitle: "Live Streaming",
  streamingEyebrow: "Virtual Ceremony",
  streamingSubtitle: "For beloved family and friends celebrating with us from afar, please join our virtual stream:",
  giftSectionTitle: "Wedding Gift",
  giftSectionEyebrow: "Token of Love",
  giftSectionDesc: "Your warm presence and prayers are the greatest gift. If you wish to send a token of love, digital registry details are below:",
  turutMengundangTitle: "Turut Mengundang",
  turutMengundangEyebrow: "Warm Regards",
  turutMengundangSubtitle: "Beloved families & friends honoring this celebration:",
  wishesSectionTitle: "Wishes & Prayers",
  wishesSectionSub: "Leave a Heartfelt Message for the Bride & Groom",
  closingQuote: "Thank you for being an essential part of our journey and sharing in the joy of our wedding day.",
  closingSub: "Warmest love, the bride & groom and our families.",
  rsvpTitle: "RSVP & Confirmation",
  rsvpBtnText: "Confirm Attendance",
};

export const DEFAULT_PREMIUM_BLUEPRINT: ThemeBlueprint = {
  themeId: "generic_premium",
  themeName: "Premium Exclusive",
  series: "premium",
  openingQuote: "True love is timeless, noble, and crowned with devotion. We request the honor of your distinguished presence as we begin our lifelong commitment.",
  openingQuoteRef: "SACRED VOWS & BLESSINGS",
  coverSubtitle: "An exclusive invitation to celebrate the eternal union of two souls.",
  openBtn: "Enter Celebration",
  quoteSectionTitle: "The Heritage",
  quoteSectionEyebrow: "MASTERPIECE OF HEARTS",
  coupleSectionTitle: "The Couple",
  coupleSectionSub: "Handcrafted love, timeless elegance.",
  eventsSectionTitle: "The Solemnity",
  eventsSectionSub: "Times & Prestigious Venue",
  storySectionTitle: "The Tapestry",
  storySectionEyebrow: "CHRONICLES OF LOVE",
  gallerySectionTitle: "The Exhibition",
  gallerySectionEyebrow: "CURATED FRAMES",
  galleryQuote: "Where hearts align under grace, eternity begins.",
  dressCodeTitle: "Dress Code",
  dressCodeEyebrow: "Attire Guide",
  dressCodeSubtitle: "Formal & distinguished attire harmonizing with our celebration:",
  streamingTitle: "Live Streaming",
  streamingEyebrow: "Virtual Attendance",
  streamingSubtitle: "For esteemed family and guests attending virtually, join our exclusive broadcast:",
  giftSectionTitle: "Wedding Registry",
  giftSectionEyebrow: "TOKEN OF RESPECT",
  giftSectionDesc: "Your blessings and presence are our highest honor. For digital tribute and wedding gifts:",
  turutMengundangTitle: "Turut Mengundang",
  turutMengundangEyebrow: "Hormat Kami",
  turutMengundangSubtitle: "Keluarga Besar & Rekan Kehormatan:",
  wishesSectionTitle: "Expressions of Grace",
  wishesSectionSub: "Inscribe Your Best Wishes for Our Lifetime",
  closingQuote: "We extend our deepest gratitude for your blessings and distinguished presence.",
  closingSub: "Respectfully, the bride, the groom & families.",
  rsvpTitle: "RSVP & Attendance",
  rsvpBtnText: "Submit RSVP",
};

/**
 * Fallback generic blueprint in case an unlisted themeId is queried.
 */
export const DEFAULT_GENERIC_BLUEPRINT: ThemeBlueprint = DEFAULT_TRADITIONAL_BLUEPRINT;

/**
 * Resolves a ThemeBlueprint for a specific themeId, gracefully overlaying any
 * admin customized settings (e.g. from theme_demo_[themeId] in AdminSetting).
 * Automatically synthesizes a theme-specific archetype if an unlisted theme is queried.
 */
export function getThemeBlueprint(
  themeId: string,
  customData?: any
): ThemeBlueprint {
  const cleanId = (themeId || "").toLowerCase().trim();
  const specificBlueprint = THEME_BLUEPRINTS[cleanId];

  let base: ThemeBlueprint;
  if (specificBlueprint) {
    base = specificBlueprint;
  } else {
    // Dynamic archetype synthesis for newly added themes
    const rawSeries = (
      customData?.series ||
      customData?.category ||
      (cleanId.includes("modern") ? "modern" : "") ||
      (cleanId.includes("premium") ? "premium" : "") ||
      "traditional"
    ).toLowerCase();

    const derivedName = customData?.themeName || (cleanId ? cleanId.charAt(0).toUpperCase() + cleanId.slice(1) : "Luxenary Theme");

    if (rawSeries.includes("modern")) {
      base = {
        ...DEFAULT_MODERN_BLUEPRINT,
        themeId: cleanId || "modern",
        themeName: derivedName,
      };
    } else if (rawSeries.includes("premium")) {
      base = {
        ...DEFAULT_PREMIUM_BLUEPRINT,
        themeId: cleanId || "premium",
        themeName: derivedName,
      };
    } else {
      base = {
        ...DEFAULT_TRADITIONAL_BLUEPRINT,
        themeId: cleanId || "traditional",
        themeName: derivedName,
      };
    }
  }

  if (!customData || typeof customData !== "object") {
    return { ...base };
  }

  const customLabels = customData.customLabels || {};

  return {
    ...base,
    openingQuote: customData.openingQuote ?? customLabels.openingQuote ?? base.openingQuote,
    openingQuoteRef: customData.openingQuoteRef ?? customLabels.openingQuoteRef ?? base.openingQuoteRef,
    coverSubtitle: customLabels.coverSubtitle ?? customData.coverSubtitle ?? base.coverSubtitle,
    openBtn: customLabels.openBtn ?? customData.openBtn ?? base.openBtn,
    quoteSectionTitle: customLabels.quoteTitle ?? customLabels.quoteSectionTitle ?? base.quoteSectionTitle,
    quoteSectionEyebrow: customLabels.quoteEyebrow ?? customLabels.quoteSectionEyebrow ?? base.quoteSectionEyebrow,
    coupleSectionEyebrow: customLabels.coupleEyebrow ?? customLabels.coupleSectionEyebrow ?? base.coupleSectionEyebrow ?? "THE COUPLE",
    coupleSectionTitle: customLabels.coupleTitle ?? customLabels.coupleSectionTitle ?? base.coupleSectionTitle,
    coupleSectionSub: customLabels.coupleSub ?? customLabels.coupleSectionSub ?? base.coupleSectionSub,
    eventsSectionTitle: customLabels.eventsTitle ?? customLabels.eventsSectionTitle ?? base.eventsSectionTitle,
    eventsSectionSub: customLabels.eventsSub ?? customLabels.eventsSectionSub ?? base.eventsSectionSub,
    storySectionTitle: customLabels.storyTitle ?? customLabels.storySectionTitle ?? base.storySectionTitle,
    storySectionEyebrow: customLabels.storyEyebrow ?? customLabels.storySectionEyebrow ?? base.storySectionEyebrow ?? "Our Journey",
    gallerySectionTitle: customLabels.galleryTitle ?? customLabels.gallerySectionTitle ?? base.gallerySectionTitle,
    gallerySectionEyebrow: customLabels.galleryEyebrow ?? customLabels.gallerySectionEyebrow ?? base.gallerySectionEyebrow,
    galleryQuote: customLabels.galleryQuote ?? base.galleryQuote,
    dressCodeTitle: customLabels.dressCodeTitle ?? base.dressCodeTitle ?? "Dress Code",
    dressCodeEyebrow: customLabels.dressCodeEyebrow ?? base.dressCodeEyebrow ?? "A Guide To",
    dressCodeSubtitle: customLabels.dressCodeSubtitle ?? base.dressCodeSubtitle ?? "Kami mengundang tamu undangan untuk mengenakan palet warna berikut:",
    streamingTitle: customLabels.streamingTitle ?? base.streamingTitle ?? "Live Streaming",
    streamingEyebrow: customLabels.streamingEyebrow ?? base.streamingEyebrow ?? "Virtual Ceremony",
    streamingSubtitle: customLabels.streamingSubtitle ?? base.streamingSubtitle ?? "Bagi keluarga & sahabat yang menyaksikan dari jauh, bergabunglah melalui siaran daring:",
    giftSectionTitle: customLabels.giftTitle ?? customLabels.giftSectionTitle ?? base.giftSectionTitle,
    giftSectionEyebrow: customLabels.giftEyebrow ?? customLabels.giftSectionEyebrow ?? base.giftSectionEyebrow,
    giftSectionDesc: customLabels.giftDesc ?? base.giftSectionDesc,
    turutMengundangTitle: customLabels.turutMengundangTitle ?? base.turutMengundangTitle ?? "Turut Mengundang",
    turutMengundangEyebrow: customLabels.turutMengundangEyebrow ?? base.turutMengundangEyebrow ?? "Keluarga Besar",
    turutMengundangSubtitle: customLabels.turutMengundangSubtitle ?? base.turutMengundangSubtitle ?? "Keluarga Besar & Kerabat yang turut berbahagia:",
    wishesSectionTitle: customLabels.wishesTitle ?? customLabels.wishesSectionTitle ?? base.wishesSectionTitle,
    wishesSectionSub: customLabels.wishesSub ?? base.wishesSectionSub,
    closingQuote: customData.closingQuote ?? customLabels.closingQuote ?? base.closingQuote,
    closingSub: customData.closingSub ?? customLabels.closingSub ?? base.closingSub,
    rsvpTitle: customLabels.rsvpTitle ?? base.rsvpTitle,
    rsvpBtnText: customLabels.rsvpBtnText ?? base.rsvpBtnText ?? "Kirim Konfirmasi & Doa",
  };
}
