/**
 * THEME BLUEPRINT REGISTRY - LUXENARY ENGINE
 * Single Source of Truth for Theme-Scoped Narratives, Quotes & Section Labels.
 * Each theme features tailored cultural/editorial defaults that reflect its unique persona.
 */

export interface ThemeBlueprint {
  themeId: string;
  themeName: string;
  series: "traditional" | "modern" | "premium";
  defaultPalette?: string;
  defaultMusicUrl?: string;
  openingQuote: string;
  openingQuoteRef: string;
  coverSubtitle: string;
  openBtn: string;
  quoteSectionTitle: string;
  quoteSectionEyebrow: string;
  openingGreeting?: string;
  coverBadge?: string;
  coupleSectionEyebrow?: string;
  coupleSectionTitle: string;
  coupleSectionSub: string;
  eventsSectionTitle: string;
  eventsSectionEyebrow?: string;
  eventsSectionSub: string;
  storySectionTitle: string;
  storySectionEyebrow?: string;
  gallerySectionTitle: string;
  gallerySectionEyebrow: string;
  galleryQuote: string;
  dressCodeTitle?: string;
  dressCodeEyebrow?: string;
  dressCodeSubtitle?: string;
  streamingTitle?: string;
  streamingEyebrow?: string;
  streamingSubtitle?: string;
  giftSectionTitle: string;
  giftSectionEyebrow: string;
  giftSectionDesc: string;
  turutMengundangTitle?: string;
  turutMengundangEyebrow?: string;
  turutMengundangSubtitle?: string;
  wishesSectionTitle: string;
  wishesSectionEyebrow?: string;
  wishesSectionSub: string;
  closingQuote: string;
  closingSub: string;
  rsvpTitle: string;
  rsvpBtnText?: string;
  vendorTitle?: string;
  vendorEyebrow?: string;
  vendorSubtitle?: string;
}

export const THEME_BLUEPRINTS: Record<string, ThemeBlueprint> = {
  // ── TRADITIONAL HERITAGE SERIES ──
  candani: {
    themeId: "candani",
    themeName: "Candani",
    series: "modern",
    defaultPalette: "terracotta",
    openingQuote: "Dan di antara tanda-tanda (kebesaran)-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya, dan Dia menjadikan di antaramu rasa kasih dan sayang.",
    openingQuoteRef: "QS. AR-RUM: 21",
    coverSubtitle: "Tanpa mengurangi rasa hormat, kami mengundang Bapak/Ibu/Saudara/i untuk menghadiri hari bahagia kami.",
    openBtn: "Buka Undangan",
    quoteSectionTitle: "Untaian Doa Suci",
    quoteSectionEyebrow: "THE SACRED UNION",
    openingGreeting: "",
    coverBadge: "THE WEDDING OF • MODERN BOTANICAL",
    coupleSectionEyebrow: "THE COUPLE",
    coupleSectionTitle: "Dua Insan",
    coupleSectionSub: "Dua Hati Bersatu Menjalin Ikatan Suci Rumah Tangga Sakinah",
    eventsSectionTitle: "Rangkaian Acara",
    eventsSectionEyebrow: "AGENDA ACARA",
    eventsSectionSub: "Waktu & Tempat Pelaksanaan Akad Nikah & Resepsi",
    storySectionTitle: "Kisah Kasih",
    storySectionEyebrow: "OUR JOURNEY",
    gallerySectionTitle: "Potret Kenangan",
    gallerySectionEyebrow: "GALLERY OF LOVE",
    galleryQuote: "Cinta sejati adalah ketika dua insan saling memuliakan dalam ketaatan dan keikhlasan.",
    dressCodeTitle: "Dress Code",
    dressCodeEyebrow: "A Guide To",
    dressCodeSubtitle: "Kami mengundang tamu undangan untuk mengenakan palet warna berikut:",
    streamingTitle: "Live Streaming",
    streamingEyebrow: "Virtual Ceremony",
    streamingSubtitle: "Bagi keluarga & sahabat yang menyaksikan dari jauh, bergabunglah melalui siaran daring:",
    giftSectionTitle: "Tanda Kasih",
    giftSectionEyebrow: "Tanda Penghormatan",
    giftSectionDesc: "Doa restu Anda merupakan karunia yang sangat berarti bagi kami. Dan jika memberi adalah ungkapan tanda kasih, Anda dapat mengirimkannya secara digital:",
    turutMengundangTitle: "Turut Mengundang",
    turutMengundangEyebrow: "Keluarga Besar",
    turutMengundangSubtitle: "Keluarga Besar & Kerabat yang turut berbahagia:",
    wishesSectionTitle: "Doa & Ucapan Restu",
    wishesSectionEyebrow: "WISHES & RSVP",
    wishesSectionSub: "Untaian Harapan & Doa Suci Dari Sahabat Serta Kerabat",
    closingQuote: "Merupakan suatu kehormatan dan kebahagiaan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir dan memberikan doa restu.",
    closingSub: "Salam hangat penuh hormat dari keluarga besar kedua mempelai.",
    rsvpTitle: "Konfirmasi Kehadiran & Doa",
    rsvpBtnText: "Kirim Konfirmasi & Doa",
    vendorTitle: "Mitra Vendor",
    vendorEyebrow: "WEDDING CREDITS",
    vendorSubtitle: "Rasa terima kasih dan penghargaan setulusnya kepada seluruh vendor yang telah membantu menyempurnakan hari bahagia kami.",
  },
  dillalucky: {
    themeId: "dillalucky",
    themeName: "Dillalucky",
    series: "traditional",
    defaultPalette: "champagne",
    openingQuote: "Nyuwun donga pangestu dhumateng Gusti Kang Akarya Jagad, mugi tansah paring berkah karaharjan dhumateng gesang kekalih.",
    openingQuoteRef: "SERAT WEDHATAMA",
    coverSubtitle: "Kanthi asma Gusti Ingkang Maha Asih, kula sakulawarga ngaturaken rawuh panjenengan sedaya.",
    openBtn: "Buka Serat Undangan",
    quoteSectionTitle: "Serat Panyuwunan",
    quoteSectionEyebrow: "PRANATAN DHOHAR",
    openingGreeting: "Kanthi Nyebat Asmaning Gusti",
    coverBadge: "SERAT PAHARGYAN • ADAT JAWA",
    coupleSectionEyebrow: "SEKAR KEKALIH",
    coupleSectionTitle: "Temanten Sekar",
    coupleSectionSub: "Nyawiji Ing Tresna Asih Sejati",
    eventsSectionTitle: "Adicara Pawiwahan",
    eventsSectionEyebrow: "TATA TITIMANGSA",
    eventsSectionSub: "Tata Wanci Saha Palenggahan Adicara",
    storySectionTitle: "Lelampahan Katresnan",
    storySectionEyebrow: "LELAMPAHAN TRESNA",
    gallerySectionTitle: "Babar Momen",
    gallerySectionEyebrow: "SESAWANGAN",
    galleryQuote: "Tresna sejati ora bakal luntur dening lumakuning mangsa.",
    dressCodeTitle: "Tata Busana",
    dressCodeEyebrow: "PRANATAN AGEMAN",
    dressCodeSubtitle: "Kula aturi para rawuh ngagem busana ingkang prayogi kanthi nuansa warna:",
    streamingTitle: "Pawiwahan Daring",
    streamingEyebrow: "LIVE STREAMING",
    streamingSubtitle: "Mugi saged hanjenengi adicara pawiwahan punika kanthi siaran langsung:",
    giftSectionTitle: "Kado Katresnan",
    giftSectionEyebrow: "TANDHA KASIH",
    giftSectionDesc: "Donga pangestu panjenengan dados berkah ingkang tanpa upami. Bilih kepareng paring tandha kasih kanthi digital:",
    turutMengundangTitle: "Turut Ngrawuhi",
    turutMengundangEyebrow: "WARGA AGUNG",
    turutMengundangSubtitle: "Kulawarga agung saha para sesepuh ingkang nderek hangayubagya:",
    wishesSectionTitle: "Atur Pangestu & Donga",
    wishesSectionEyebrow: "ATUR PANGESTU",
    wishesSectionSub: "Pangestu Tulus Saking Para Pinisepuh Saha Mitra",
    closingQuote: "Matur nuwun sanget awit saking sih kadarman panjenengan sedaya ingkang sampun kersa rawuh saha paring berkah pangestu.",
    closingSub: "Kula sakulawarga agung ngaturaken gunging panuwun ingkang tanpa pepindhan.",
    rsvpTitle: "Konfirmasi Rawuh & Donga",
    rsvpBtnText: "Kintun Konfirmasi & Donga",
    vendorTitle: "Panyengkuyung Adicara",
    vendorEyebrow: "WEDDING CREDITS",
    vendorSubtitle: "Gunging panuwun dhumateng sedaya mitra ingkang sampun hangrencangi lumampahing adicara punika.",
  },
  prameswari: {
    themeId: "prameswari",
    themeName: "Prameswari",
    series: "traditional",
    defaultPalette: "champagne",
    openingQuote: "Dan di antara tanda-tanda kebesaran-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya, dan Dia menjadikan di antaramu rasa kasih dan sayang.",
    openingQuoteRef: "QS. AR-RUM : 21",
    coverSubtitle: "Dengan penuh rasa syukur dan hormat, kami mengundang kehadiran Bapak/Ibu/Sahabat tercinta.",
    openBtn: "Buka Undangan",
    quoteSectionTitle: "Untaian Doa Suci",
    quoteSectionEyebrow: "WALIMATUL 'URS",
    openingGreeting: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    coverBadge: "PAWIWAHAN AGENG • KERATON",
    coupleSectionEyebrow: "SEKAR TEMANTEN",
    coupleSectionTitle: "Sang Mempelai",
    coupleSectionSub: "Dua Jiwa Bersatu Dalam Ikatan Agung Berpayung Ridho Ilahi",
    eventsSectionTitle: "Agenda Acara",
    eventsSectionEyebrow: "RANGKAIAN PAWIWAHAN",
    eventsSectionSub: "Waktu & Tempat Pelaksanaan Akad Nikah & Resepsi",
    storySectionTitle: "Kisah Kasih",
    storySectionEyebrow: "LELAMPAHAN CINTA",
    gallerySectionTitle: "Momen Sakral",
    gallerySectionEyebrow: "GALERI KENANGAN",
    galleryQuote: "Dua hati yang tertaut dalam ikatan suci pernikahan berpayung ridho Ilahi.",
    dressCodeTitle: "Tata Busana",
    dressCodeEyebrow: "DRESS CODE",
    dressCodeSubtitle: "Kami mengundang Bapak/Ibu/Saudara/i untuk mengenakan busana bernuansa:",
    streamingTitle: "Live Streaming",
    streamingEyebrow: "SIARAN LANGSUNG",
    streamingSubtitle: "Bagi kerabat dan sahabat yang berhalangan hadir secara fisik, saksikan prosesi secara daring:",
    giftSectionTitle: "Tanda Kasih",
    giftSectionEyebrow: "UNGKAPAN CINTA",
    giftSectionDesc: "Kehadiran dan doa Anda adalah anugerah terbesar bagi kami. Jika ingin memberikan tanda kasih secara cashless:",
    turutMengundangTitle: "Turut Mengundang",
    turutMengundangEyebrow: "KELUARGA BESAR",
    turutMengundangSubtitle: "Keluarga besar & handai taulan yang turut berbahagia:",
    wishesSectionTitle: "Doa & Restu",
    wishesSectionEyebrow: "DOA & PANGESTU",
    wishesSectionSub: "Kirimkan Pesan Manis & Doa Tulus Untuk Mempelai",
    closingQuote: "Tiada yang lebih berharga selain doa tulus dan restu yang Anda curahkan untuk mengawali bahtera rumah tangga kami.",
    closingSub: "Keluarga Besar Kedua Mempelai",
    rsvpTitle: "Konfirmasi Kehadiran",
    rsvpBtnText: "Kirim Konfirmasi & Doa",
    vendorTitle: "Mitra Vendor",
    vendorEyebrow: "WEDDING CREDITS",
    vendorSubtitle: "Penghargaan tulus kepada seluruh vendor yang telah membantu mewujudkan hari bahagia kami.",
  },
  mayang: {
    themeId: "mayang",
    themeName: "Mayang",
    series: "modern",
    defaultPalette: "sage",
    openingQuote: "Dua hati yang bersatu dalam cinta dan kasih sayang, melangkah bersama mengarungi samudera kehidupan yang penuh berkah.",
    openingQuoteRef: "THE WEDDING CELEBRATION",
    coverSubtitle: "Dengan penuh rasa syukur dan sukacita, kami mengundang Anda untuk merayakan awal kisah cinta kami.",
    openBtn: "Buka Undangan",
    quoteSectionTitle: "Untaian Doa Suci",
    quoteSectionEyebrow: "THE SACRED UNION",
    openingGreeting: "",
    coverBadge: "THE WEDDING OF",
    coupleSectionEyebrow: "THE COUPLE",
    coupleSectionTitle: "Kedua Mempelai",
    coupleSectionSub: "Bersatu dalam janji suci dan cinta abadi",
    eventsSectionTitle: "Rangkaian Acara",
    eventsSectionEyebrow: "AGENDA ACARA",
    eventsSectionSub: "Waktu & Tempat Pelaksanaan Akad Serta Resepsi",
    storySectionTitle: "Kisah Kasih Kami",
    storySectionEyebrow: "OUR JOURNEY",
    gallerySectionTitle: "Galeri Kenangan",
    gallerySectionEyebrow: "MOMENTS OF LOVE",
    galleryQuote: "Setiap potret mengabadikan sejuta makna tentang bagaimana cinta bertumbuh dan bersemi.",
    dressCodeTitle: "Dress Code",
    dressCodeEyebrow: "PANDUAN BUSANA",
    dressCodeSubtitle: "Kami mengundang tamu undangan untuk mengenakan busana dengan nuansa warna berikut:",
    streamingTitle: "Live Streaming",
    streamingEyebrow: "SIARAN LANGSUNG",
    streamingSubtitle: "Bagi keluarga & sahabat yang menyaksikan dari jauh, saksikan prosesi pernikahan kami secara daring:",
    giftSectionTitle: "Tanda Kasih",
    giftSectionEyebrow: "WEDDING GIFT",
    giftSectionDesc: "Doa restu Anda adalah karunia yang sangat berarti. Bagi yang ingin memberikan tanda kasih secara digital:",
    turutMengundangTitle: "Turut Mengundang",
    turutMengundangEyebrow: "KELUARGA BESAR",
    turutMengundangSubtitle: "Keluarga besar & kerabat yang turut berbahagia:",
    wishesSectionTitle: "Ucapan & Doa",
    wishesSectionEyebrow: "WISHES & PRAYERS",
    wishesSectionSub: "Sampaikan doa dan harapan terbaik Anda bagi kedua mempelai",
    closingQuote: "Terima kasih atas doa restu dan kehadiran yang telah melengkapi kebahagiaan hari istimewa kami.",
    closingSub: "Salam hangat dari kami yang berbahagia.",
    rsvpTitle: "Konfirmasi Kehadiran",
    rsvpBtnText: "Kirim Konfirmasi & Doa",
    vendorTitle: "Mitra Vendor",
    vendorEyebrow: "WEDDING CREDITS",
    vendorSubtitle: "Terima kasih sebesar-besarnya kepada seluruh mitra dan vendor yang membantu terwujudnya acara ini.",
  },
  badrika: {
    themeId: "badrika",
    themeName: "Badrika",
    series: "modern",
    defaultPalette: "emerald",
    openingQuote: "Maha Suci Allah yang telah menciptakan makhluk-Nya berpasang-pasangan. Izinkan kami menyempurnakan separuh agama ini.",
    openingQuoteRef: "QS. AZ-ZARIYAT : 49",
    coverSubtitle: "Tanpa mengurangi rasa hormat, perkenankan kami mengundang Anda untuk merayakan cinta kami.",
    openBtn: "Buka Undangan",
    quoteSectionTitle: "Ayat & Doa Suci",
    quoteSectionEyebrow: "THE SACRED UNION",
    openingGreeting: "",
    coverBadge: "THE WEDDING OF",
    coupleSectionEyebrow: "THE COUPLE",
    coupleSectionTitle: "Mempelai Berbahagia",
    coupleSectionSub: "Langkah Pertama Menuju Keabadian",
    eventsSectionTitle: "Rangkaian Acara",
    eventsSectionEyebrow: "AGENDA ACARA",
    eventsSectionSub: "Waktu & Tempat Pelaksanaan Akad Serta Resepsi",
    storySectionTitle: "Kisah Kasih Kami",
    storySectionEyebrow: "OUR JOURNEY",
    gallerySectionTitle: "Galeri Foto",
    gallerySectionEyebrow: "POTRET KENANGAN",
    galleryQuote: "Di setiap langkah kami saling menemukan, di setiap doa kami saling menguatkan.",
    dressCodeTitle: "Dress Code",
    dressCodeEyebrow: "A GUIDE TO",
    dressCodeSubtitle: "Kami mengundang tamu undangan untuk mengenakan palet warna berikut:",
    streamingTitle: "Live Streaming",
    streamingEyebrow: "VIRTUAL CEREMONY",
    streamingSubtitle: "Bagi keluarga & sahabat yang menyaksikan dari jauh, bergabunglah melalui siaran daring:",
    giftSectionTitle: "Tanda Kasih",
    giftSectionEyebrow: "WEDDING GIFT",
    giftSectionDesc: "Doa restu Anda merupakan karunia yang sangat berarti bagi kami. Jika berkenan memberi kado digital:",
    turutMengundangTitle: "Turut Mengundang",
    turutMengundangEyebrow: "KELUARGA BESAR",
    turutMengundangSubtitle: "Keluarga Besar & Kerabat yang turut berbahagia:",
    wishesSectionTitle: "Ucapan & Doa",
    wishesSectionEyebrow: "WISHES & RSVP",
    wishesSectionSub: "Kirimkan Pesan Manis Untuk Mempelai",
    closingQuote: "Kehadiran dan doa restu Anda adalah pelita yang menerangi langkah awal perjalanan hidup kami.",
    closingSub: "Keluarga Besar Mempelai",
    rsvpTitle: "Konfirmasi Kehadiran & Doa",
    rsvpBtnText: "Kirim Konfirmasi & Doa",
    vendorTitle: "Mitra Vendor",
    vendorEyebrow: "WEDDING CREDITS",
    vendorSubtitle: "Rasa terima kasih setulusnya kepada para vendor yang telah menyempurnakan hari bahagia kami.",
  },
  lagaligo: {
    themeId: "lagaligo",
    themeName: "La Galigo",
    series: "traditional",
    defaultPalette: "bugis",
    openingQuote: "Maha Suci Allah yang telah menciptakan makhluk-Nya berpasang-pasangan. Perkenankanlah kami merangkai kasih sayang yang Kau ciptakan di antara putra-putri kami dalam ikatan suci pernikahan.",
    openingQuoteRef: "QS. AR-RUM : 21",
    coverSubtitle: "Dengan penuh rasa syukur dan hormat, kami mengundang kehadiran Bapak/Ibu/Sahabat tercinta.",
    openBtn: "Buka Undangan",
    quoteSectionTitle: "Untaian Doa",
    quoteSectionEyebrow: "WALIMATUL 'URS",
    openingGreeting: "﷽",
    coverBadge: "SURE' I LA GALIGO • WALIMATUL 'URS",
    coupleSectionEyebrow: "DUA INSAN",
    coupleSectionTitle: "Mempelai Bahagia",
    coupleSectionSub: "Maha Suci Allah yang telah menciptakan makhluk-Nya berpasang-pasangan.",
    eventsSectionTitle: "Rangkaian Acara",
    eventsSectionEyebrow: "AGENDA ACARA",
    eventsSectionSub: "Waktu & Tempat Pelaksanaan Akad Serta Resepsi",
    storySectionTitle: "Kisah Kasih Kami",
    storySectionEyebrow: "OUR JOURNEY",
    gallerySectionTitle: "Potret Kenangan",
    gallerySectionEyebrow: "MOMEN BAHAGIA",
    galleryQuote: "Dua hati yang tertaut dalam ikatan suci pernikahan berpayung ridho Ilahi.",
    dressCodeTitle: "Dress Code",
    dressCodeEyebrow: "PANDUAN BUSANA",
    dressCodeSubtitle: "Nuansa busana pernikahan adat Bugis / Maroon & Gold:",
    streamingTitle: "Live Streaming",
    streamingEyebrow: "SIARAN LANGSUNG",
    streamingSubtitle: "Saksikan siaran langsung prosesi pernikahan kami secara daring:",
    giftSectionTitle: "Tanda Kasih",
    giftSectionEyebrow: "WEDDING GIFT",
    giftSectionDesc: "Doa restu Anda merupakan karunia yang sangat berarti bagi kami. Jika berkenan memberi kado digital:",
    turutMengundangTitle: "Turut Mengundang",
    turutMengundangEyebrow: "KELUARGA BESAR",
    turutMengundangSubtitle: "Keluarga Besar & Kerabat yang turut berbahagia:",
    wishesSectionTitle: "Buku Tamu & Kehadiran",
    wishesSectionEyebrow: "BUKU TAMU & RESTU",
    wishesSectionSub: "Untaian doa dan konfirmasi kehadiran Anda merupakan kado terindah bagi kami.",
    closingQuote: "Merupakan suatu kehormatan dan kebahagiaan bagi kami apabila Bapak/Ibu/Sahabat berkenan hadir dan memberikan doa restu bagi kami.",
    closingSub: "Keluarga Besar Kedua Mempelai",
    rsvpTitle: "Konfirmasi Kehadiran",
    rsvpBtnText: "Kirim Ucapan & Konfirmasi",
    vendorTitle: "Mitra Vendor",
    vendorEyebrow: "WEDDING CREDITS",
    vendorSubtitle: "Rasa terima kasih kepada mitra yang telah membantu mewujudkan momen bahagia kami.",
  },
  toraja: {
    themeId: "toraja",
    themeName: "Toraja",
    series: "traditional",
    defaultPalette: "toraja",
    openingQuote: "Misa' kada dipotuo, pantan kada dipomate. Keberkahan dan kedamaian senantiasa melingkupi dua insan yang dipersatukan dalam ikatan suci pernikahan adat Toraja.",
    openingQuoteRef: "KADA DIPOTUO TORAJA",
    coverSubtitle: "Kurresumanga'. Tanpa mengurangi rasa hormat, kami mengundang Bapak/Ibu/Saudara/i untuk menghadiri hari bahagia kami.",
    openBtn: "Buka Undangan",
    quoteSectionTitle: "Petuah & Doa Restu",
    quoteSectionEyebrow: "RAMPUAN LOLO",
    openingGreeting: "Kurre Sumanga'",
    coverBadge: "THE WEDDING OF • ADAT TORAJA",
    coupleSectionEyebrow: "DUA INSAN",
    coupleSectionTitle: "Dua Insan",
    coupleSectionSub: "Dua Hati Dipersatukan dalam Ikatan Suci Tongkonan",
    eventsSectionTitle: "Rangkaian Acara",
    eventsSectionEyebrow: "RAMPUAN LOLO",
    eventsSectionSub: "Waktu & Tempat Pelaksanaan Ibadah / Akad & Resepsi",
    storySectionTitle: "Kisah Kasih",
    storySectionEyebrow: "OUR JOURNEY",
    gallerySectionTitle: "Kenangan Bersama",
    gallerySectionEyebrow: "OUR MOMENTS",
    galleryQuote: "Bagaikan ukiran Passura' yang abadi di dinding Tongkonan, demikianlah cinta kami terpatri selamanya.",
    dressCodeTitle: "Dress Code",
    dressCodeEyebrow: "A Guide To",
    dressCodeSubtitle: "Nuansa busana adat Toraja / Crimson & Gold:",
    streamingTitle: "Live Streaming",
    streamingEyebrow: "Virtual Ceremony",
    streamingSubtitle: "Saksikan prosesi pernikahan kami secara daring:",
    giftSectionTitle: "Tanda Kasih",
    giftSectionEyebrow: "AMPLOP DIGITAL",
    giftSectionDesc: "Doa restu Anda merupakan karunia terindah bagi kami. Jika ingin memberikan tanda kasih secara digital:",
    turutMengundangTitle: "Turut Mengundang",
    turutMengundangEyebrow: "Keluarga Besar",
    turutMengundangSubtitle: "Rumpun Keluarga Besar Tongkonan yang turut berbahagia:",
    wishesSectionTitle: "Untaian Doa",
    wishesSectionEyebrow: "KADA DIPOTUO",
    wishesSectionSub: "Doa & Harapan Suci dari Sahabat dan Handai Taulan",
    closingQuote: "Kurresumanga' pole' paraa. Suatu kehormatan dan kebahagiaan tak terhingga atas kehadiran serta doa restu Bapak/Ibu/Saudara/i.",
    closingSub: "Hormat kami dari kedua rumpun keluarga besar mempelai.",
    rsvpTitle: "Konfirmasi Kehadiran",
    rsvpBtnText: "Kirim Konfirmasi & Doa",
    vendorTitle: "Mitra Vendor",
    vendorEyebrow: "WEDDING CREDITS",
    vendorSubtitle: "Terima kasih kepada seluruh pihak dan vendor yang telah menyempurnakan perayaan suci ini.",
  },
  rantepao: {
    themeId: "rantepao",
    themeName: "Rantepao",
    series: "traditional",
    defaultPalette: "toraja",
    openingQuote: "Misa' kada dipotuo, pantan kada dipomate. Bersatu kita teguh dalam janji suci, berpadu dua rumpun keluarga besar adat Toraja di bumi Rantepao.",
    openingQuoteRef: "PETUAH KELUARGA BESAR TORAJA",
    coverSubtitle: "Kurre Sumanga'. Merupakan kehormatan dan kebahagiaan bagi kami sekeluarga atas kehadiran dan doa restu Bapak/Ibu/Saudara/i.",
    openBtn: "Buka Undangan",
    quoteSectionTitle: "Untaian Doa & Restu",
    quoteSectionEyebrow: "RAMPUAN LOLO RANTEPAO",
    openingGreeting: "Kurre Sumanga'",
    coverBadge: "THE WEDDING OF • RANTEPAO TORAJA",
    coupleSectionEyebrow: "MEMPELAI BAHAGIA",
    coupleSectionTitle: "Mempelai Bahagia",
    coupleSectionSub: "Dua Insan yang Dipersatukan oleh Kasih dan Restu Leluhur",
    eventsSectionTitle: "Rangkaian Perayaan",
    eventsSectionEyebrow: "RAMPUAN LOLO",
    eventsSectionSub: "Jadwal Prosesi Ibadah Pemberkatan / Akad & Resepsi Pernikahan",
    storySectionTitle: "Kisah Kasih",
    storySectionEyebrow: "OUR STORY",
    gallerySectionTitle: "Galeri Kenangan",
    gallerySectionEyebrow: "MOMENTS OF LOVE",
    galleryQuote: "Di bawah naungan langit Rantepao, ikatan cinta dan kesetiaan kami terpatri teguh sepanjang masa.",
    dressCodeTitle: "Panduan Busana",
    dressCodeEyebrow: "Dress Code",
    dressCodeSubtitle: "Nuansa busana adat Toraja / Crimson & Gold:",
    streamingTitle: "Prosesi Virtual",
    streamingEyebrow: "Live Streaming",
    streamingSubtitle: "Saksikan prosesi pernikahan kami secara daring:",
    giftSectionTitle: "Tanda Kasih Digital",
    giftSectionEyebrow: "WEDDING GIFT",
    giftSectionDesc: "Doa restu Anda merupakan karunia terindah bagi kami. Bagi yang ingin berbagi tanda kasih secara digital:",
    turutMengundangTitle: "Turut Mengundang",
    turutMengundangEyebrow: "Keluarga Besar",
    turutMengundangSubtitle: "Rumpun Keluarga Besar yang turut bersukacita:",
    wishesSectionTitle: "Ucapan & Doa",
    wishesSectionEyebrow: "PANGESTU TORAJA",
    wishesSectionSub: "Kirimkan untaian doa dan harapan terbaik Anda untuk kedua mempelai",
    closingQuote: "Kurresumanga' pole' parannu. Terima kasih setulus hati atas kehadiran, doa restu, dan limpahan kasih Bapak/Ibu/Saudara/i sekalian.",
    closingSub: "Kami yang berbahagia, seluruh keluarga besar kedua mempelai.",
    rsvpTitle: "Konfirmasi Kehadiran",
    rsvpBtnText: "Kirim Konfirmasi & Doa",
    vendorTitle: "Mitra Vendor",
    vendorEyebrow: "WEDDING CREDITS",
    vendorSubtitle: "Terima kasih kepada seluruh mitra yang telah menyempurnakan hari bahagia kami.",
  },
  makale: {
    themeId: "makale",
    themeName: "Makale",
    series: "traditional",
    defaultPalette: "toraja",
    openingQuote: "Misa' kada dipotuo, pantan kada dipomate. Di bawah lindungan bukit kars Buntu Burake dan kesejukan Makale Tana Toraja, dua hati dan rumpun keluarga berpadu dalam ikrar suci.",
    openingQuoteRef: "FILOSOFI ADAT TANA TORAJA",
    coverSubtitle: "Kurre Sumanga'. Merupakan kehormatan dan kebahagiaan bagi kami sekeluarga atas kehadiran dan doa restu Bapak/Ibu/Saudara/i.",
    openBtn: "Buka Undangan",
    quoteSectionTitle: "Untaian Doa & Restu",
    quoteSectionEyebrow: "RAMPUAN LOLO MAKALE",
    openingGreeting: "Kurre Sumanga'",
    coverBadge: "THE WEDDING OF • MAKALE TANA TORAJA",
    coupleSectionEyebrow: "MEMPELAI BAHAGIA",
    coupleSectionTitle: "Mempelai Bahagia",
    coupleSectionSub: "Dua Insan yang Dipersatukan oleh Kasih dan Restu Leluhur",
    eventsSectionTitle: "Rangkaian Perayaan",
    eventsSectionEyebrow: "RAMPUAN LOLO",
    eventsSectionSub: "Jadwal Prosesi Ibadah Pemberkatan / Akad & Resepsi Pernikahan",
    storySectionTitle: "Kisah Kasih",
    storySectionEyebrow: "OUR STORY",
    gallerySectionTitle: "Galeri Kenangan",
    gallerySectionEyebrow: "MOMENTS OF LOVE",
    galleryQuote: "Di bumi Makale yang agung, janji suci kami abadi dalam naungan adat dan restu semesta.",
    dressCodeTitle: "Panduan Busana",
    dressCodeEyebrow: "Dress Code",
    dressCodeSubtitle: "Nuansa busana adat Toraja / Crimson & Gold:",
    streamingTitle: "Prosesi Virtual",
    streamingEyebrow: "Live Streaming",
    streamingSubtitle: "Saksikan prosesi pernikahan kami secara daring:",
    giftSectionTitle: "Tanda Kasih Digital",
    giftSectionEyebrow: "WEDDING GIFT",
    giftSectionDesc: "Doa restu Anda merupakan karunia terindah bagi kami. Bagi yang ingin berbagi tanda kasih secara digital:",
    turutMengundangTitle: "Turut Mengundang",
    turutMengundangEyebrow: "Keluarga Besar",
    turutMengundangSubtitle: "Rumpun Keluarga Besar yang turut bersukacita:",
    wishesSectionTitle: "Ucapan & Doa",
    wishesSectionEyebrow: "PANGESTU MAKALE",
    wishesSectionSub: "Kirimkan untaian doa dan harapan terbaik Anda untuk kedua mempelai",
    closingQuote: "Kurresumanga' pole' parannu. Terima kasih setulus hati atas kehadiran, doa restu, dan limpahan kasih Bapak/Ibu/Saudara/i sekalian.",
    closingSub: "Kami yang berbahagia, seluruh keluarga besar kedua mempelai.",
    rsvpTitle: "Konfirmasi Kehadiran",
    rsvpBtnText: "Kirim Konfirmasi & Doa",
    vendorTitle: "Mitra Vendor",
    vendorEyebrow: "WEDDING CREDITS",
    vendorSubtitle: "Terima kasih kepada seluruh mitra yang telah menyempurnakan hari bahagia kami.",
  },
  bugis: {
    themeId: "bugis",
    themeName: "Bugis",
    series: "traditional",
    defaultPalette: "bugis",
    openingQuote: "Sipakatau, sipakalebbi, sipakainge. Narekko purai sikaleng, tessisarakang lino ahera. Dengan memohon ridho dan rahmat Allah SWT, kami bermaksud melangsungkan ikatan suci pernikahan adat Bugis.",
    openingQuoteRef: "PAPPASENG TO RIOLO",
    coverSubtitle: "Kurru Sumanga'. Tanpa mengurangi rasa hormat, kami mengundang Bapak/Ibu/Saudara/i untuk menghadiri hari bahagia kami.",
    openBtn: "Buka Undangan",
    quoteSectionTitle: "Petuah & Doa Restu",
    quoteSectionEyebrow: "PAPPASENG TO RIOLO",
    openingGreeting: "Kurru Sumanga'",
    coverBadge: "THE WEDDING OF • ADAT BUGIS",
    coupleSectionEyebrow: "DUA INSAN",
    coupleSectionTitle: "Dua Insan",
    coupleSectionSub: "Dua Hati Dipersatukan dalam Ikatan Suci Saoraja",
    eventsSectionTitle: "Rangkaian Acara",
    eventsSectionEyebrow: "MAPPABOTTING",
    eventsSectionSub: "Waktu & Tempat Pelaksanaan Akad Nikah & Resepsi",
    storySectionTitle: "Kisah Kasih",
    storySectionEyebrow: "OUR JOURNEY",
    gallerySectionTitle: "Kenangan Bersama",
    gallerySectionEyebrow: "OUR MOMENTS",
    galleryQuote: "Bagaikan benang emas dalam tenun lipa' sabbe, cinta kami terajut indah dan abadi sepanjang masa.",
    dressCodeTitle: "Dress Code",
    dressCodeEyebrow: "A Guide To",
    dressCodeSubtitle: "Nuansa busana adat Bugis / Maroon & Gold:",
    streamingTitle: "Live Streaming",
    streamingEyebrow: "Virtual Ceremony",
    streamingSubtitle: "Saksikan prosesi pernikahan kami secara daring:",
    giftSectionTitle: "Tanda Kasih",
    giftSectionEyebrow: "AMPLOP DIGITAL",
    giftSectionDesc: "Doa restu Anda merupakan karunia terindah bagi kami. Jika ingin memberikan tanda kasih secara digital:",
    turutMengundangTitle: "Turut Mengundang",
    turutMengundangEyebrow: "Keluarga Besar",
    turutMengundangSubtitle: "Keluarga Besar & Kerabat yang turut berbahagia:",
    wishesSectionTitle: "Untaian Doa",
    wishesSectionEyebrow: "PAPPASENG & DOA",
    wishesSectionSub: "Doa & Harapan Suci dari Sahabat dan Handai Taulan",
    closingQuote: "Kurru sumanga' polo ampu. Suatu kehormatan dan kebahagiaan tak terhingga atas kehadiran serta doa restu Bapak/Ibu/Saudara/i.",
    closingSub: "Hormat kami dari kedua keluarga besar mempelai.",
    rsvpTitle: "Konfirmasi Kehadiran",
    rsvpBtnText: "Kirim Konfirmasi & Doa",
    vendorTitle: "Mitra Vendor",
    vendorEyebrow: "WEDDING CREDITS",
    vendorSubtitle: "Terima kasih kepada seluruh pihak dan vendor yang telah menyempurnakan perayaan suci ini.",
  },
  makassar: {
    themeId: "makassar",
    themeName: "Makassar",
    series: "traditional",
    defaultPalette: "makassar",
    openingQuote: "Bajiki passiriki, sombere' na malabbiri. Siri' na pacce menjadi landasan teguh dua insan yang berpadu dalam ikatan suci pernikahan adat Makassar.",
    openingQuoteRef: "PASANG RI BURA'NE",
    coverSubtitle: "Tabe' kipammopporang. Tanpa mengurangi rasa hormat, kami mengundang Bapak/Ibu/Saudara/i untuk menghadiri hari bahagia kami.",
    openBtn: "Buka Undangan",
    quoteSectionTitle: "Petuah & Doa Restu",
    quoteSectionEyebrow: "PASANG RI BURA'NE",
    openingGreeting: "Tabe' Kipammopporang",
    coverBadge: "THE WEDDING OF • ADAT MAKASSAR",
    coupleSectionEyebrow: "DUA INSAN",
    coupleSectionTitle: "Dua Insan",
    coupleSectionSub: "Dua Jiwa Berlayar Bersama Mengarungi Bahtera Kehidupan",
    eventsSectionTitle: "Rangkaian Acara",
    eventsSectionEyebrow: "BOTING ADAT",
    eventsSectionSub: "Waktu & Tempat Pelaksanaan Akad Nikah & Resepsi",
    storySectionTitle: "Kisah Kasih",
    storySectionEyebrow: "OUR JOURNEY",
    gallerySectionTitle: "Kenangan Bersama",
    gallerySectionEyebrow: "OUR MOMENTS",
    galleryQuote: "Bagaikan keteguhan Kapal Phinisi mengarungi samudra, cinta kami kokoh berlayar menuju ridho ilahi.",
    dressCodeTitle: "Dress Code",
    dressCodeEyebrow: "A Guide To",
    dressCodeSubtitle: "Nuansa busana adat Makassar / Royal Navy & Gold:",
    streamingTitle: "Live Streaming",
    streamingEyebrow: "Virtual Ceremony",
    streamingSubtitle: "Saksikan prosesi pernikahan kami secara daring:",
    giftSectionTitle: "Tanda Kasih",
    giftSectionEyebrow: "AMPLOP DIGITAL",
    giftSectionDesc: "Doa restu Anda merupakan karunia terindah bagi kami. Jika ingin memberikan tanda kasih secara digital:",
    turutMengundangTitle: "Turut Mengundang",
    turutMengundangEyebrow: "Keluarga Besar",
    turutMengundangSubtitle: "Keluarga Besar & Kerabat yang turut berbahagia:",
    wishesSectionTitle: "Untaian Doa",
    wishesSectionEyebrow: "PASANG & DOA",
    wishesSectionSub: "Doa & Harapan Suci dari Sahabat dan Handai Taulan",
    closingQuote: "Tarima kasi' lompo. Suatu kehormatan dan kebahagiaan tak terhingga atas kehadiran serta doa restu Bapak/Ibu/Saudara/i.",
    closingSub: "Hormat kami dari kedua keluarga besar mempelai.",
    rsvpTitle: "Konfirmasi Kehadiran",
    rsvpBtnText: "Kirim Konfirmasi & Doa",
    vendorTitle: "Mitra Vendor",
    vendorEyebrow: "WEDDING CREDITS",
    vendorSubtitle: "Terima kasih kepada seluruh pihak dan vendor yang telah menyempurnakan perayaan suci ini.",
  },

  bone: {
    themeId: "bone",
    themeName: "Bone",
    series: "traditional",
    defaultPalette: "bone",
    openingQuote: "Sipakatau, sipakalebbi, sipakainge. Di bumi Arung Palakka dan keagungan Saoraja Lamurukung, dua rumpun keluarga bangsawan Bone berpadu dalam ikrar suci.",
    openingQuoteRef: "PAPPASENG TO BONE",
    coverSubtitle: "Kurru Sumanga'. Tanpa mengurangi rasa hormat, kami mengundang Bapak/Ibu/Saudara/i untuk menghadiri hari bahagia kami.",
    openBtn: "Buka Undangan",
    quoteSectionTitle: "Petuah & Doa Restu",
    quoteSectionEyebrow: "PAPPASENG TO BONE",
    openingGreeting: "Kurru Sumanga'",
    coverBadge: "THE WEDDING OF • BUGIS BONE",
    coupleSectionEyebrow: "DUA INSAN",
    coupleSectionTitle: "Dua Insan",
    coupleSectionSub: "Dua Hati Dipersatukan dalam Ikatan Suci Adat Bone",
    eventsSectionTitle: "Rangkaian Acara",
    eventsSectionEyebrow: "MAPPABOTTING BONE",
    eventsSectionSub: "Waktu & Tempat Pelaksanaan Akad Nikah & Resepsi",
    storySectionTitle: "Kisah Kasih",
    storySectionEyebrow: "OUR JOURNEY",
    gallerySectionTitle: "Kenangan Bersama",
    gallerySectionEyebrow: "OUR MOMENTS",
    galleryQuote: "Bagaikan keagungan Songkok To Bone, cinta dan kesetiaan kami teranyam kokoh bermahkotakan restu Ilahi.",
    dressCodeTitle: "Dress Code",
    dressCodeEyebrow: "A Guide To",
    dressCodeSubtitle: "Nuansa busana adat Bugis / Maroon & Gold:",
    streamingTitle: "Live Streaming",
    streamingEyebrow: "Virtual Ceremony",
    streamingSubtitle: "Saksikan prosesi pernikahan kami secara daring:",
    giftSectionTitle: "Tanda Kasih",
    giftSectionEyebrow: "AMPLOP DIGITAL",
    giftSectionDesc: "Doa restu Anda merupakan karunia terindah bagi kami. Jika ingin memberikan tanda kasih secara digital:",
    turutMengundangTitle: "Turut Mengundang",
    turutMengundangEyebrow: "Keluarga Besar",
    turutMengundangSubtitle: "Keluarga Besar & Kerabat yang turut berbahagia:",
    wishesSectionTitle: "Untaian Doa",
    wishesSectionEyebrow: "PAPPASENG BONE",
    wishesSectionSub: "Doa & Harapan Suci dari Sahabat dan Handai Taulan",
    closingQuote: "Kurru sumanga' polo ampu. Suatu kehormatan dan kebahagiaan tak terhingga atas kehadiran serta doa restu Bapak/Ibu/Saudara/i.",
    closingSub: "Hormat kami dari kedua keluarga besar mempelai.",
    rsvpTitle: "Konfirmasi Kehadiran",
    rsvpBtnText: "Kirim Konfirmasi & Doa",
    vendorTitle: "Mitra Vendor",
    vendorEyebrow: "WEDDING CREDITS",
    vendorSubtitle: "Terima kasih kepada seluruh pihak dan vendor yang telah menyempurnakan perayaan suci ini.",
  },

  wajo: {
    themeId: "wajo",
    themeName: "Wajo",
    series: "traditional",
    defaultPalette: "wajo",
    openingQuote: "Maradeka to Wajo-e, naia tompo' ri ade'na. Dalam ketulusan cinta dan keindahan sutera Sengkang, kami berpadu mengikat janji suci pernikahan.",
    openingQuoteRef: "PAPPASENG TO WAJO",
    coverSubtitle: "Kurru Sumanga'. Tanpa mengurangi rasa hormat, kami mengundang Bapak/Ibu/Saudara/i untuk menghadiri hari bahagia kami.",
    openBtn: "Buka Undangan",
    quoteSectionTitle: "Petuah & Doa Restu",
    quoteSectionEyebrow: "PAPPASENG TO WAJO",
    openingGreeting: "Kurru Sumanga'",
    coverBadge: "THE WEDDING OF • BUGIS WAJO",
    coupleSectionEyebrow: "DUA INSAN",
    coupleSectionTitle: "Dua Insan",
    coupleSectionSub: "Dua Hati Dipersatukan dalam Ikatan Suci Adat Wajo",
    eventsSectionTitle: "Rangkaian Acara",
    eventsSectionEyebrow: "MAPPABOTTING WAJO",
    eventsSectionSub: "Waktu & Tempat Pelaksanaan Akad Nikah & Resepsi",
    storySectionTitle: "Kisah Kasih",
    storySectionEyebrow: "OUR JOURNEY",
    gallerySectionTitle: "Kenangan Bersama",
    gallerySectionEyebrow: "OUR MOMENTS",
    galleryQuote: "Seindah tenun sutera Wajo yang berkilau di tepian Danau Tempe, demikianlah cinta kami terajut abadi.",
    dressCodeTitle: "Dress Code",
    dressCodeEyebrow: "A Guide To",
    dressCodeSubtitle: "Nuansa busana adat Bugis / Maroon & Gold:",
    streamingTitle: "Live Streaming",
    streamingEyebrow: "Virtual Ceremony",
    streamingSubtitle: "Saksikan prosesi pernikahan kami secara daring:",
    giftSectionTitle: "Tanda Kasih",
    giftSectionEyebrow: "AMPLOP DIGITAL",
    giftSectionDesc: "Doa restu Anda merupakan karunia terindah bagi kami. Jika ingin memberikan tanda kasih secara digital:",
    turutMengundangTitle: "Turut Mengundang",
    turutMengundangEyebrow: "Keluarga Besar",
    turutMengundangSubtitle: "Keluarga Besar & Kerabat yang turut berbahagia:",
    wishesSectionTitle: "Untaian Doa",
    wishesSectionEyebrow: "PAPPASENG WAJO",
    wishesSectionSub: "Doa & Harapan Suci dari Sahabat dan Handai Taulan",
    closingQuote: "Kurru sumanga' polo ampu. Suatu kehormatan dan kebahagiaan tak terhingga atas kehadiran serta doa restu Bapak/Ibu/Saudara/i.",
    closingSub: "Hormat kami dari kedua keluarga besar mempelai.",
    rsvpTitle: "Konfirmasi Kehadiran",
    rsvpBtnText: "Kirim Konfirmasi & Doa",
    vendorTitle: "Mitra Vendor",
    vendorEyebrow: "WEDDING CREDITS",
    vendorSubtitle: "Terima kasih kepada seluruh pihak dan vendor yang telah menyempurnakan perayaan suci ini.",
  },

  soppeng: {
    themeId: "soppeng",
    themeName: "Soppeng",
    series: "traditional",
    defaultPalette: "soppeng",
    openingQuote: "Tepu nalisu ada to riolo, mate ri tani-tani, malompo ri ada tongeng. Di bumi Latemmamala Soppeng, dua hati bersatu dalam naungan adat dan kehormatan.",
    openingQuoteRef: "PAPPASENG TO SOPPENG",
    coverSubtitle: "Kurru Sumanga'. Tanpa mengurangi rasa hormat, kami mengundang Bapak/Ibu/Saudara/i untuk menghadiri hari bahagia kami.",
    openBtn: "Buka Undangan",
    quoteSectionTitle: "Petuah & Doa Restu",
    quoteSectionEyebrow: "PAPPASENG TO SOPPENG",
    openingGreeting: "Kurru Sumanga'",
    coverBadge: "THE WEDDING OF • BUGIS SOPPENG",
    coupleSectionEyebrow: "DUA INSAN",
    coupleSectionTitle: "Dua Insan",
    coupleSectionSub: "Dua Hati Dipersatukan dalam Ikatan Suci Adat Soppeng",
    eventsSectionTitle: "Rangkaian Acara",
    eventsSectionEyebrow: "MAPPABOTTING SOPPENG",
    eventsSectionSub: "Waktu & Tempat Pelaksanaan Akad Nikah & Resepsi",
    storySectionTitle: "Kisah Kasih",
    storySectionEyebrow: "OUR JOURNEY",
    gallerySectionTitle: "Kenangan Bersama",
    gallerySectionEyebrow: "OUR MOMENTS",
    galleryQuote: "Di bawah keteduhan bumi Soppeng yang damai, langkah cinta kami berpadu menuju mahligai rumah tangga yang sakinah.",
    dressCodeTitle: "Dress Code",
    dressCodeEyebrow: "A Guide To",
    dressCodeSubtitle: "Nuansa busana adat Bugis / Maroon & Gold:",
    streamingTitle: "Live Streaming",
    streamingEyebrow: "Virtual Ceremony",
    streamingSubtitle: "Saksikan prosesi pernikahan kami secara daring:",
    giftSectionTitle: "Tanda Kasih",
    giftSectionEyebrow: "AMPLOP DIGITAL",
    giftSectionDesc: "Doa restu Anda merupakan karunia terindah bagi kami. Jika ingin memberikan tanda kasih secara digital:",
    turutMengundangTitle: "Turut Mengundang",
    turutMengundangEyebrow: "Keluarga Besar",
    turutMengundangSubtitle: "Keluarga Besar & Kerabat yang turut berbahagia:",
    wishesSectionTitle: "Untaian Doa",
    wishesSectionEyebrow: "PAPPASENG SOPPENG",
    wishesSectionSub: "Doa & Harapan Suci dari Sahabat dan Handai Taulan",
    closingQuote: "Kurru sumanga' polo ampu. Suatu kehormatan dan kebahagiaan tak terhingga atas kehadiran serta doa restu Bapak/Ibu/Saudara/i.",
    closingSub: "Hormat kami dari kedua keluarga besar mempelai.",
    rsvpTitle: "Konfirmasi Kehadiran",
    rsvpBtnText: "Kirim Konfirmasi & Doa",
    vendorTitle: "Mitra Vendor",
    vendorEyebrow: "WEDDING CREDITS",
    vendorSubtitle: "Terima kasih kepada seluruh pihak dan vendor yang telah menyempurnakan perayaan suci ini.",
  },

  gowa: {
    themeId: "gowa",
    themeName: "Gowa",
    series: "traditional",
    defaultPalette: "gowa",
    openingQuote: "Bajiki passiriki, sombere' na malabbiri. Di bumi bersejarah Somba Opu dan Balla Lompoa Gowa, dua insan berpadu dalam ikatan suci adat Makassar yang agung.",
    openingQuoteRef: "PASANG RI GOWA",
    coverSubtitle: "Tabe' kipammopporang. Tanpa mengurangi rasa hormat, kami mengundang Bapak/Ibu/Saudara/i untuk menghadiri hari bahagia kami.",
    openBtn: "Buka Undangan",
    quoteSectionTitle: "Petuah & Doa Restu",
    quoteSectionEyebrow: "PASANG RI GOWA",
    openingGreeting: "Tabe' Kipammopporang",
    coverBadge: "THE WEDDING OF • MAKASSAR GOWA",
    coupleSectionEyebrow: "DUA INSAN",
    coupleSectionTitle: "Dua Insan",
    coupleSectionSub: "Dua Hati Dipersatukan dalam Ikatan Suci Kesultanan Gowa",
    eventsSectionTitle: "Rangkaian Acara",
    eventsSectionEyebrow: "BOTING GOWA",
    eventsSectionSub: "Waktu & Tempat Pelaksanaan Akad Nikah & Resepsi",
    storySectionTitle: "Kisah Kasih",
    storySectionEyebrow: "OUR JOURNEY",
    gallerySectionTitle: "Kenangan Bersama",
    gallerySectionEyebrow: "OUR MOMENTS",
    galleryQuote: "Keteguhan cinta kami berdiri kokoh laksana benteng Somba Opu, senantiasa berpayung siri' na pacce dan ridho Ilahi.",
    dressCodeTitle: "Dress Code",
    dressCodeEyebrow: "A Guide To",
    dressCodeSubtitle: "Nuansa busana adat Makassar / Royal Navy & Gold:",
    streamingTitle: "Live Streaming",
    streamingEyebrow: "Virtual Ceremony",
    streamingSubtitle: "Saksikan prosesi pernikahan kami secara daring:",
    giftSectionTitle: "Tanda Kasih",
    giftSectionEyebrow: "AMPLOP DIGITAL",
    giftSectionDesc: "Doa restu Anda merupakan karunia terindah bagi kami. Jika ingin memberikan tanda kasih secara digital:",
    turutMengundangTitle: "Turut Mengundang",
    turutMengundangEyebrow: "Keluarga Besar",
    turutMengundangSubtitle: "Keluarga Besar & Kerabat yang turut berbahagia:",
    wishesSectionTitle: "Untaian Doa",
    wishesSectionEyebrow: "PASANG GOWA",
    wishesSectionSub: "Doa & Harapan Suci dari Sahabat dan Handai Taulan",
    closingQuote: "Tarima kasi' lompo. Suatu kehormatan dan kebahagiaan tak terhingga atas kehadiran serta doa restu Bapak/Ibu/Saudara/i.",
    closingSub: "Hormat kami dari kedua keluarga besar mempelai.",
    rsvpTitle: "Konfirmasi Kehadiran",
    rsvpBtnText: "Kirim Konfirmasi & Doa",
    vendorTitle: "Mitra Vendor",
    vendorEyebrow: "WEDDING CREDITS",
    vendorSubtitle: "Terima kasih kepada seluruh pihak dan vendor yang telah menyempurnakan perayaan suci ini.",
  },

  maros: {
    themeId: "maros",
    themeName: "Maros",
    series: "traditional",
    defaultPalette: "maros",
    openingQuote: "Kukalengngi atengku ri barakkana Butta Salewangang. Di bawah megahnya bukit karst Rammang-Rammang Maros, kami mengucap janji suci pernikahan yang kekal.",
    openingQuoteRef: "FILOSOFI BUTTA SALEWANGANG MAROS",
    coverSubtitle: "Tabe' kipammopporang. Tanpa mengurangi rasa hormat, kami mengundang Bapak/Ibu/Saudara/i untuk menghadiri hari bahagia kami.",
    openBtn: "Buka Undangan",
    quoteSectionTitle: "Petuah & Doa Restu",
    quoteSectionEyebrow: "PASANG RI MARUSU'",
    openingGreeting: "Tabe' Kipammopporang",
    coverBadge: "THE WEDDING OF • MAKASSAR MAROS",
    coupleSectionEyebrow: "DUA INSAN",
    coupleSectionTitle: "Dua Insan",
    coupleSectionSub: "Dua Hati Dipersatukan dalam Ikatan Suci Adat Maros",
    eventsSectionTitle: "Rangkaian Acara",
    eventsSectionEyebrow: "BOTING MAROS",
    eventsSectionSub: "Waktu & Tempat Pelaksanaan Akad Nikah & Resepsi",
    storySectionTitle: "Kisah Kasih",
    storySectionEyebrow: "OUR JOURNEY",
    gallerySectionTitle: "Kenangan Bersama",
    gallerySectionEyebrow: "OUR MOMENTS",
    galleryQuote: "Seindah alam Maros yang menyejukkan jiwa, cinta kami mekar abadi dalam berkah dan restu semesta.",
    dressCodeTitle: "Dress Code",
    dressCodeEyebrow: "A Guide To",
    dressCodeSubtitle: "Nuansa busana adat Makassar / Royal Navy & Gold:",
    streamingTitle: "Live Streaming",
    streamingEyebrow: "Virtual Ceremony",
    streamingSubtitle: "Saksikan prosesi pernikahan kami secara daring:",
    giftSectionTitle: "Tanda Kasih",
    giftSectionEyebrow: "AMPLOP DIGITAL",
    giftSectionDesc: "Doa restu Anda merupakan karunia terindah bagi kami. Jika ingin memberikan tanda kasih secara digital:",
    turutMengundangTitle: "Turut Mengundang",
    turutMengundangEyebrow: "Keluarga Besar",
    turutMengundangSubtitle: "Keluarga Besar & Kerabat yang turut berbahagia:",
    wishesSectionTitle: "Untaian Doa",
    wishesSectionEyebrow: "PASANG MAROS",
    wishesSectionSub: "Doa & Harapan Suci dari Sahabat dan Handai Taulan",
    closingQuote: "Tarima kasi' lompo. Suatu kehormatan dan kebahagiaan tak terhingga atas kehadiran serta doa restu Bapak/Ibu/Saudara/i.",
    closingSub: "Hormat kami dari kedua keluarga besar mempelai.",
    rsvpTitle: "Konfirmasi Kehadiran",
    rsvpBtnText: "Kirim Konfirmasi & Doa",
    vendorTitle: "Mitra Vendor",
    vendorEyebrow: "WEDDING CREDITS",
    vendorSubtitle: "Terima kasih kepada seluruh pihak dan vendor yang telah menyempurnakan perayaan suci ini.",
  },

  takalar: {
    themeId: "takalar",
    themeName: "Takalar",
    series: "traditional",
    defaultPalette: "takalar",
    openingQuote: "Ammempo ri panrannuangku, siri' na pacce nipakateteng. Dari bumi pesisir Sanrobone Takalar, dua hati berpadu mengarungi samudera kehidupan bersama.",
    openingQuoteRef: "PASANG RI BUTTA PANRANNUANGKU",
    coverSubtitle: "Tabe' kipammopporang. Tanpa mengurangi rasa hormat, kami mengundang Bapak/Ibu/Saudara/i untuk menghadiri hari bahagia kami.",
    openBtn: "Buka Undangan",
    quoteSectionTitle: "Petuah & Doa Restu",
    quoteSectionEyebrow: "PASANG RI SANROBONE",
    openingGreeting: "Tabe' Kipammopporang",
    coverBadge: "THE WEDDING OF • MAKASSAR TAKALAR",
    coupleSectionEyebrow: "DUA INSAN",
    coupleSectionTitle: "Dua Insan",
    coupleSectionSub: "Dua Hati Dipersatukan dalam Ikatan Suci Adat Takalar",
    eventsSectionTitle: "Rangkaian Acara",
    eventsSectionEyebrow: "BOTING TAKALAR",
    eventsSectionSub: "Waktu & Tempat Pelaksanaan Akad Nikah & Resepsi",
    storySectionTitle: "Kisah Kasih",
    storySectionEyebrow: "OUR JOURNEY",
    gallerySectionTitle: "Kenangan Bersama",
    gallerySectionEyebrow: "OUR MOMENTS",
    galleryQuote: "Di bumi Takalar yang penuh berkah dan harapan, janji setia kami terpatri teguh sepanjang usia.",
    dressCodeTitle: "Dress Code",
    dressCodeEyebrow: "A Guide To",
    dressCodeSubtitle: "Nuansa busana adat Makassar / Royal Navy & Gold:",
    streamingTitle: "Live Streaming",
    streamingEyebrow: "Virtual Ceremony",
    streamingSubtitle: "Saksikan prosesi pernikahan kami secara daring:",
    giftSectionTitle: "Tanda Kasih",
    giftSectionEyebrow: "AMPLOP DIGITAL",
    giftSectionDesc: "Doa restu Anda merupakan karunia terindah bagi kami. Jika ingin memberikan tanda kasih secara digital:",
    turutMengundangTitle: "Turut Mengundang",
    turutMengundangEyebrow: "Keluarga Besar",
    turutMengundangSubtitle: "Keluarga Besar & Kerabat yang turut berbahagia:",
    wishesSectionTitle: "Untaian Doa",
    wishesSectionEyebrow: "PASANG TAKALAR",
    wishesSectionSub: "Doa & Harapan Suci dari Sahabat dan Handai Taulan",
    closingQuote: "Tarima kasi' lompo. Suatu kehormatan dan kebahagiaan tak terhingga atas kehadiran serta doa restu Bapak/Ibu/Saudara/i.",
    closingSub: "Hormat kami dari kedua keluarga besar mempelai.",
    rsvpTitle: "Konfirmasi Kehadiran",
    rsvpBtnText: "Kirim Konfirmasi & Doa",
    vendorTitle: "Mitra Vendor",
    vendorEyebrow: "WEDDING CREDITS",
    vendorSubtitle: "Terima kasih kepada seluruh pihak dan vendor yang telah menyempurnakan perayaan suci ini.",
  },

  bulukumba: {
    themeId: "bulukumba",
    themeName: "Bulukumba",
    series: "traditional",
    defaultPalette: "bulukumba",
    openingQuote: "Tallang sipahua, manynyameng kininnawa. Di bumi Panrita Lopi Bulukumba, bahtera cinta kami berlayar menuju pelabuhan sakinah mawaddah warahmah.",
    openingQuoteRef: "FILOSOFI PANRITA LOPI BULUKUMBA",
    coverSubtitle: "Tabe' kipammopporang. Tanpa mengurangi rasa hormat, kami mengundang Bapak/Ibu/Saudara/i untuk menghadiri hari bahagia kami.",
    openBtn: "Buka Undangan",
    quoteSectionTitle: "Petuah & Doa Restu",
    quoteSectionEyebrow: "PASANG RI BUTTA PANRITA LOPI",
    openingGreeting: "Tabe' Kipammopporang",
    coverBadge: "THE WEDDING OF • MAKASSAR BULUKUMBA",
    coupleSectionEyebrow: "DUA INSAN",
    coupleSectionTitle: "Dua Insan",
    coupleSectionSub: "Dua Hati Dipersatukan dalam Ikatan Suci Panrita Lopi",
    eventsSectionTitle: "Rangkaian Acara",
    eventsSectionEyebrow: "BOTING BULUKUMBA",
    eventsSectionSub: "Waktu & Tempat Pelaksanaan Akad Nikah & Resepsi",
    storySectionTitle: "Kisah Kasih",
    storySectionEyebrow: "OUR JOURNEY",
    gallerySectionTitle: "Kenangan Bersama",
    gallerySectionEyebrow: "OUR MOMENTS",
    galleryQuote: "Sebagaimana tangguhnya Phinisi mengarungi ombak samudera, demikian teguh cinta dan kesetiaan kami menempuh perjalanan hidup.",
    dressCodeTitle: "Dress Code",
    dressCodeEyebrow: "A Guide To",
    dressCodeSubtitle: "Nuansa busana adat Makassar / Royal Navy & Gold:",
    streamingTitle: "Live Streaming",
    streamingEyebrow: "Virtual Ceremony",
    streamingSubtitle: "Saksikan prosesi pernikahan kami secara daring:",
    giftSectionTitle: "Tanda Kasih",
    giftSectionEyebrow: "AMPLOP DIGITAL",
    giftSectionDesc: "Doa restu Anda merupakan karunia terindah bagi kami. Jika ingin memberikan tanda kasih secara digital:",
    turutMengundangTitle: "Turut Mengundang",
    turutMengundangEyebrow: "Keluarga Besar",
    turutMengundangSubtitle: "Keluarga Besar & Kerabat yang turut berbahagia:",
    wishesSectionTitle: "Untaian Doa",
    wishesSectionEyebrow: "PASANG BULUKUMBA",
    wishesSectionSub: "Doa & Harapan Suci dari Sahabat dan Handai Taulan",
    closingQuote: "Tarima kasi' lompo. Suatu kehormatan dan kebahagiaan tak terhingga atas kehadiran serta doa restu Bapak/Ibu/Saudara/i.",
    closingSub: "Hormat kami dari kedua keluarga besar mempelai.",
    rsvpTitle: "Konfirmasi Kehadiran",
    rsvpBtnText: "Kirim Konfirmasi & Doa",
    vendorTitle: "Mitra Vendor",
    vendorEyebrow: "WEDDING CREDITS",
    vendorSubtitle: "Terima kasih kepada seluruh pihak dan vendor yang telah menyempurnakan perayaan suci ini.",
  },

  // ── MODERN EDITORIAL SERIES ──
  ameera: {
    themeId: "ameera",
    themeName: "Ameera",
    series: "modern",
    defaultPalette: "burgundy",
    openingQuote: "In all the world, there is no heart for me like yours. In all the world, there is no love for you like mine.",
    openingQuoteRef: "MAYA ANGELOU",
    coverSubtitle: "We warmly invite you to celebrate our union and witness the beginning of our forever.",
    openBtn: "Open Invitation",
    quoteSectionTitle: "Words of Love",
    quoteSectionEyebrow: "THE SACRED VOWS",
    openingGreeting: "With Joyful Hearts",
    coverBadge: "THE WEDDING CELEBRATION",
    coupleSectionEyebrow: "THE COUPLE",
    coupleSectionTitle: "The Couple",
    coupleSectionSub: "Two paths, one destination: forever together.",
    eventsSectionTitle: "The Celebration",
    eventsSectionEyebrow: "TIMELINE",
    eventsSectionSub: "Save the Date & Location",
    storySectionTitle: "Our Love Story",
    storySectionEyebrow: "OUR CHAPTERS",
    gallerySectionTitle: "Captured Moments",
    gallerySectionEyebrow: "THE GALLERY",
    galleryQuote: "Every love story is beautiful, but ours is our absolute favorite.",
    dressCodeTitle: "Dress Code",
    dressCodeEyebrow: "ATTIRE GUIDE",
    dressCodeSubtitle: "We invite our lovely guests to wear colors in harmony with:",
    streamingTitle: "Virtual Ceremony",
    streamingEyebrow: "LIVE STREAM",
    streamingSubtitle: "For family and friends celebrating with us from afar:",
    giftSectionTitle: "Wedding Gift",
    giftSectionEyebrow: "TOKEN OF LOVE",
    giftSectionDesc: "Your presence at our wedding is the greatest gift of all. However, should you wish to honor us with a gift, a cashless gesture is warmly welcomed:",
    turutMengundangTitle: "Warmly Invited By",
    turutMengundangEyebrow: "HONORED FAMILIES",
    turutMengundangSubtitle: "Joined in celebration by our beloved families:",
    wishesSectionTitle: "Wishes & Prayers",
    wishesSectionEyebrow: "WISHES & RSVP",
    wishesSectionSub: "Leave a Warm Message for the Couple",
    closingQuote: "Thank you for being part of our story and celebrating this unforgettable chapter with us.",
    closingSub: "With love and gratitude, the happy couple & families.",
    rsvpTitle: "RSVP & Best Wishes",
    rsvpBtnText: "Send RSVP & Wishes",
    vendorTitle: "Wedding Credits",
    vendorEyebrow: "CREATIVE TEAM",
    vendorSubtitle: "Sincere gratitude to all vendors who contributed to making this celebration possible.",
  },
  chronicle: {
    themeId: "chronicle",
    themeName: "Chronicle",
    series: "modern",
    defaultPalette: "monochrome",
    openingQuote: "And suddenly all the love songs were about you. Here begins the greatest adventure of our lives.",
    openingQuoteRef: "THE LOVE CHRONICLES",
    coverSubtitle: "An exclusive invitation to witness and celebrate the union of two hearts.",
    openBtn: "Read Invitation",
    quoteSectionTitle: "The Prologue",
    quoteSectionEyebrow: "CHAPTER ZERO",
    openingGreeting: "An Exclusive Invitation",
    coverBadge: "THE WEDDING CHRONICLE • SPECIAL ISSUE",
    coupleSectionEyebrow: "THE PROTAGONISTS",
    coupleSectionTitle: "The Protagonists",
    coupleSectionSub: "Where love found its true rhythm.",
    eventsSectionTitle: "The Schedule",
    eventsSectionEyebrow: "THE ITINERARY",
    eventsSectionSub: "Details of Holy Matrimony & Reception",
    storySectionTitle: "Chapters of Us",
    storySectionEyebrow: "CHRONICLE OF US",
    gallerySectionTitle: "Visual Chronicle",
    gallerySectionEyebrow: "PHOTO ESSAY",
    galleryQuote: "Captured in time, framed by love, cherished forever.",
    dressCodeTitle: "Dress Code",
    dressCodeEyebrow: "STYLE GUIDE",
    dressCodeSubtitle: "Monochrome elegance or formal dark attire is appreciated:",
    streamingTitle: "Live Broadcast",
    streamingEyebrow: "VIRTUAL CEREMONY",
    streamingSubtitle: "Stream our holy matrimony and celebration live online:",
    giftSectionTitle: "Wedding Registry",
    giftSectionEyebrow: "TOKEN OF APPRECIATION",
    giftSectionDesc: "Your prayers are our greatest treasure. For those wishing to send a digital wedding gift:",
    turutMengundangTitle: "Honorary Mentions",
    turutMengundangEyebrow: "FAMILY & LOVED ONES",
    turutMengundangSubtitle: "Celebrating alongside both distinguished families:",
    wishesSectionTitle: "Guest Messages",
    wishesSectionEyebrow: "GUEST MESSAGES",
    wishesSectionSub: "Share Your Warmest Blessings",
    closingQuote: "The best chapter is the one we write together with everyone we cherish.",
    closingSub: "Warmest regards from both families.",
    rsvpTitle: "RSVP & Guestbook",
    rsvpBtnText: "Confirm Attendance",
    vendorTitle: "Production Credits",
    vendorEyebrow: "CURATED BY",
    vendorSubtitle: "With appreciation to the talented team who crafted this memorable occasion.",
  },
  lumina: {
    themeId: "lumina",
    themeName: "Lumina",
    series: "modern",
    defaultPalette: "champagne",
    openingQuote: "Love does not consist in gazing at each other, but in looking outward together in the same direction.",
    openingQuoteRef: "ANTOINE DE SAINT-EXUPÉRY",
    coverSubtitle: "Together with our families, we joyfully invite you to our wedding celebration.",
    openBtn: "Explore Invitation",
    quoteSectionTitle: "Reflection",
    quoteSectionEyebrow: "A GLIMPSE OF ETERNITY",
    openingGreeting: "Together With Our Families",
    coverBadge: "THE WEDDING CELEBRATION",
    coupleSectionEyebrow: "THE BRIDE & GROOM",
    coupleSectionTitle: "The Bride & Groom",
    coupleSectionSub: "Illuminated by love, blessed with faith.",
    eventsSectionTitle: "The Gathering",
    eventsSectionEyebrow: "THE PROGRAMME",
    eventsSectionSub: "Ceremony & Celebration Details",
    storySectionTitle: "How It Began",
    storySectionEyebrow: "OUR STORY",
    gallerySectionTitle: "Moments of Light",
    gallerySectionEyebrow: "EXQUISITE GALLERY",
    galleryQuote: "In the gentle warmth of love, everything finds its meaning.",
    dressCodeTitle: "Dress Code",
    dressCodeEyebrow: "COLOR PALETTE",
    dressCodeSubtitle: "Guests are invited to dress in formal attire with these tones:",
    streamingTitle: "Live Streaming",
    streamingEyebrow: "VIRTUAL CEREMONY",
    streamingSubtitle: "Witness our wedding vows live from anywhere in the world:",
    giftSectionTitle: "Wedding Gift",
    giftSectionEyebrow: "SEND LOVE",
    giftSectionDesc: "Your blessings mean the world to us. Should you wish to send a token of love electronically:",
    turutMengundangTitle: "Warmly Invited By",
    turutMengundangEyebrow: "BELOVED FAMILIES",
    turutMengundangSubtitle: "With joy and gratitude from both families:",
    wishesSectionTitle: "Warm Wishes",
    wishesSectionEyebrow: "WARM WISHES",
    wishesSectionSub: "Send Love and Prayers for Our Journey",
    closingQuote: "Your presence and sincere prayers will complete the radiance of our joyous celebration.",
    closingSub: "With endless gratitude, from both families.",
    rsvpTitle: "RSVP & Confirmation",
    rsvpBtnText: "Submit RSVP",
    vendorTitle: "Wedding Partners",
    vendorEyebrow: "CREDITS",
    vendorSubtitle: "Our warmest thanks to every vendor who made this milestone unforgettable.",
  },
  papercut: {
    themeId: "papercut",
    themeName: "Papercut",
    series: "modern",
    defaultPalette: "terracotta",
    openingQuote: "Setiap helai kisah yang kita rajut bermuara pada satu janji: setia mengarungi hidup bersama hingga usia senja.",
    openingQuoteRef: "UNTUK SELAMANYA",
    coverSubtitle: "Kisah cinta kami terukir indah, dan kami ingin membagikan kebahagiaan ini bersama Anda.",
    openBtn: "Buka Undangan",
    quoteSectionTitle: "Rajutan Kisah",
    quoteSectionEyebrow: "JANJI SETIA",
    openingGreeting: "Salam Hangat & Doa Restu",
    coverBadge: "UNDANGAN PERNIKAHAN RESMI",
    coupleSectionEyebrow: "KEDUA MEMPELAI",
    coupleSectionTitle: "Dua Mempelai",
    coupleSectionSub: "Dipersatukan oleh takdir, diteguhkan oleh cinta.",
    eventsSectionTitle: "Agenda Acara",
    eventsSectionEyebrow: "SUSUNAN ACARA",
    eventsSectionSub: "Waktu & Lokasi Penyelenggaraan",
    storySectionTitle: "Alur Waktu",
    storySectionEyebrow: "JEJAK WAKTU",
    gallerySectionTitle: "Potret Momen",
    gallerySectionEyebrow: "GALERI CINTA",
    galleryQuote: "Keindahan cinta terpancar dari kebersamaan yang tulus dan bersahaja.",
    dressCodeTitle: "Panduan Busana",
    dressCodeEyebrow: "DRESS CODE",
    dressCodeSubtitle: "Kami mengundang tamu tercinta untuk mengenakan pakaian bernuansa:",
    streamingTitle: "Siaran Langsung",
    streamingEyebrow: "LIVE STREAMING",
    streamingSubtitle: "Saksikan prosesi pernikahan kami secara daring melalui tautan:",
    giftSectionTitle: "Tanda Kasih",
    giftSectionEyebrow: "KADO PERNIKAHAN",
    giftSectionDesc: "Doa restu Anda adalah karunia terindah. Jika berkenan memberikan tanda kasih secara digital:",
    turutMengundangTitle: "Turut Mengundang",
    turutMengundangEyebrow: "KELUARGA BESAR",
    turutMengundangSubtitle: "Keluarga besar yang senantiasa mendoakan dan mendampingi:",
    wishesSectionTitle: "Ungkapan Doa",
    wishesSectionEyebrow: "UNGKAPAN DOA",
    wishesSectionSub: "Tuliskan Ucapan & Doa Tulus Anda",
    closingQuote: "Terima kasih atas segala doa, tawa, dan kebersamaan yang senantiasa menemani perjalanan kami.",
    closingSub: "Salam hangat penuh cinta dari kami berdua.",
    rsvpTitle: "Konfirmasi Kehadiran",
    rsvpBtnText: "Kirim Konfirmasi Kehadiran",
    vendorTitle: "Mitra Vendor",
    vendorEyebrow: "WEDDING CREDITS",
    vendorSubtitle: "Terima kasih kepada semua pihak yang telah mewujudkan keindahan hari ini.",
  },
  solaria: {
    themeId: "solaria",
    themeName: "Solaria",
    series: "modern",
    defaultPalette: "champagne",
    openingQuote: "Wherever you go, I will go; and wherever you lodge, I will lodge. Your journey is my journey, forever.",
    openingQuoteRef: "PROMISE OF HORIZON",
    coverSubtitle: "Under the warm golden glow of dusk, we invite you to share our happiest moment.",
    openBtn: "Step Inside",
    quoteSectionTitle: "Doa & Harapan",
    quoteSectionEyebrow: "WALIMATUL 'URSY",
    openingGreeting: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    coverBadge: "WALIMATUL 'URSY • MODERN SUNSET",
    coupleSectionEyebrow: "THE COUPLE",
    coupleSectionTitle: "The Couple",
    coupleSectionSub: "Under one sky, stepping into infinity.",
    eventsSectionTitle: "The Events",
    eventsSectionEyebrow: "THE SCHEDULE",
    eventsSectionSub: "Time & Venue of Our Wedding Day",
    storySectionTitle: "The Journey",
    storySectionEyebrow: "OUR JOURNEY",
    gallerySectionTitle: "Sunlit Memories",
    gallerySectionEyebrow: "PHOTO SHOWCASE",
    galleryQuote: "True love shines through every season, constant and unwavering.",
    dressCodeTitle: "Dress Code",
    dressCodeEyebrow: "PALETTE INSPIRATION",
    dressCodeSubtitle: "Sunset gold, warm earth, or festive formal attire:",
    streamingTitle: "Live Streaming",
    streamingEyebrow: "VIRTUAL CEREMONY",
    streamingSubtitle: "Join us virtually to witness our sacred matrimonial ceremony:",
    giftSectionTitle: "Wedding Gift",
    giftSectionEyebrow: "SHARED LOVE",
    giftSectionDesc: "Having you celebrate with us is the greatest honor. If you wish to send a cashless gift:",
    turutMengundangTitle: "Turut Mengundang",
    turutMengundangEyebrow: "KELUARGA BESAR",
    turutMengundangSubtitle: "Keluarga besar dari kedua belah pihak yang berbahagia:",
    wishesSectionTitle: "Guest Messages",
    wishesSectionEyebrow: "GUEST MESSAGES",
    wishesSectionSub: "Write a Note of Celebration",
    closingQuote: "Thank you for gracing our special day with your warmth, love, and blessing.",
    closingSub: "Love and light always from our families.",
    rsvpTitle: "RSVP & Greetings",
    rsvpBtnText: "Send RSVP & Wishes",
    vendorTitle: "Wedding Credits",
    vendorEyebrow: "PARTNERS",
    vendorSubtitle: "Sincere appreciation to everyone who brought this golden day to life.",
  },
  wave: {
    themeId: "wave",
    themeName: "Wave",
    series: "modern",
    defaultPalette: "midnight",
    openingQuote: "Like ocean waves returning to the shore, true love always finds its way home.",
    openingQuoteRef: "OCEAN OF DEVOTION",
    coverSubtitle: "Please join us as we celebrate our new beginning on this momentous day.",
    openBtn: "Open Invitation",
    quoteSectionTitle: "Currents of Love",
    quoteSectionEyebrow: "THE RHYTHM",
    openingGreeting: "Warmest Welcome",
    coverBadge: "THE WEDDING CELEBRATION",
    coupleSectionEyebrow: "THE COUPLE",
    coupleSectionTitle: "The Couple",
    coupleSectionSub: "Flowing together in harmony, boundless and true.",
    eventsSectionTitle: "Wedding Schedule",
    eventsSectionEyebrow: "ORDER OF EVENTS",
    eventsSectionSub: "When & Where We Tie the Knot",
    storySectionTitle: "Tides of Time",
    storySectionEyebrow: "TIDES OF TIME",
    gallerySectionTitle: "Gallery of Memories",
    gallerySectionEyebrow: "TIMELESS MOMENTS",
    galleryQuote: "Love is the anchor that holds our hearts through every tide.",
    dressCodeTitle: "Dress Code",
    dressCodeEyebrow: "STYLE GUIDE",
    dressCodeSubtitle: "Coastal chic, deep navy, or ocean-inspired formal attire:",
    streamingTitle: "Live Broadcast",
    streamingEyebrow: "ONLINE STREAM",
    streamingSubtitle: "Watch our wedding ceremony live across the waves:",
    giftSectionTitle: "Gift & Registry",
    giftSectionEyebrow: "TOKEN OF BLESSING",
    giftSectionDesc: "Your presence is our present. Should you wish to bless us with a cashless wedding gift:",
    turutMengundangTitle: "Joined in Celebration",
    turutMengundangEyebrow: "HONORED FAMILIES",
    turutMengundangSubtitle: "With warm regards from both families and loved ones:",
    wishesSectionTitle: "Wishes & Warmth",
    wishesSectionEyebrow: "WISHES & WARMTH",
    wishesSectionSub: "Send Your Best Prayers for the Couple",
    closingQuote: "Your blessing is the sweetest gentle tide carrying us into our new journey.",
    closingSub: "Warmest regards from both families.",
    rsvpTitle: "RSVP & Confirmation",
    rsvpBtnText: "Confirm Attendance",
    vendorTitle: "Creative Partners",
    vendorEyebrow: "CREDITS",
    vendorSubtitle: "Thank you to the extraordinary vendors and friends behind this day.",
  },

  // ── PREMIUM EXCLUSIVE SERIES ──
  artisan: {
    themeId: "artisan",
    themeName: "Artisan",
    series: "premium",
    defaultPalette: "terracotta",
    openingQuote: "True art is love made visible. We are profoundly honored to share this sacred milestone with you.",
    openingQuoteRef: "THE ARTISAN VOWS",
    coverSubtitle: "Together with our esteemed families, we request the honor of your gracious presence.",
    openBtn: "Enter Celebration",
    quoteSectionTitle: "The Heritage",
    quoteSectionEyebrow: "MASTERPIECE OF HEARTS",
    openingGreeting: "With Great Joy & Honor",
    coverBadge: "THE WEDDING CELEBRATION",
    coupleSectionEyebrow: "THE COUPLE",
    coupleSectionTitle: "The Couple",
    coupleSectionSub: "Handcrafted love, timeless elegance.",
    eventsSectionTitle: "The Solemnity",
    eventsSectionEyebrow: "PROGRAMME OF EVENTS",
    eventsSectionSub: "Ceremony & Reception Program",
    storySectionTitle: "The Tapestry",
    storySectionEyebrow: "THE TAPESTRY",
    gallerySectionTitle: "The Exhibition",
    gallerySectionEyebrow: "CURATED FRAMES",
    galleryQuote: "A masterwork composed of love, trust, and perpetual devotion.",
    dressCodeTitle: "Dress Code",
    dressCodeEyebrow: "ATTIRE GUIDELINES",
    dressCodeSubtitle: "Earthy tones, warm neutrals, and organic textures are celebrated:",
    streamingTitle: "Live Broadcast",
    streamingEyebrow: "VIRTUAL CEREMONY",
    streamingSubtitle: "Experience our wedding vows live via online stream:",
    giftSectionTitle: "Wedding Registry",
    giftSectionEyebrow: "TOKEN OF RESPECT",
    giftSectionDesc: "Your prayers are the finest tribute to our new beginning. For digital wedding gifts:",
    turutMengundangTitle: "Honored Families",
    turutMengundangEyebrow: "FAMILY ARCHIVE",
    turutMengundangSubtitle: "With highest respect from the bride's and groom's families:",
    wishesSectionTitle: "Expressions of Grace",
    wishesSectionEyebrow: "EXPRESSIONS OF GRACE",
    wishesSectionSub: "Convey Your Heartfelt Prayers & Best Wishes",
    closingQuote: "We extend our deepest gratitude for your blessings and distinguished presence.",
    closingSub: "Respectfully, the bride, the groom & families.",
    rsvpTitle: "RSVP & Attendance",
    rsvpBtnText: "Send RSVP",
    vendorTitle: "Artisan Collective",
    vendorEyebrow: "CREDITS",
    vendorSubtitle: "Honoring the artisans and vendors who crafted every detail with love.",
  },
  aurelia: {
    themeId: "aurelia",
    themeName: "Aurelia",
    series: "premium",
    defaultPalette: "champagne",
    openingQuote: "Love is golden when crowned with sincerity, reverence, and unconditional devotion.",
    openingQuoteRef: "AURELIA GOLDEN ARCHIVE",
    coverSubtitle: "An exclusive invitation to celebrate the eternal union of two souls.",
    openBtn: "View Invitation",
    quoteSectionTitle: "Golden Devotion",
    quoteSectionEyebrow: "CELEBRATING ETERNITY",
    openingGreeting: "In Celebration of Love",
    coverBadge: "THE ROYAL WEDDING CELEBRATION",
    coupleSectionEyebrow: "THE BRIDE & GROOM",
    coupleSectionTitle: "The Bride & Groom",
    coupleSectionSub: "Reflecting grace, bound in sacred unity.",
    eventsSectionTitle: "The Itinerary",
    eventsSectionEyebrow: "THE ITINERARY",
    eventsSectionSub: "Times & Prestigious Venue",
    storySectionTitle: "The Golden Era",
    storySectionEyebrow: "THE GOLDEN ERA",
    gallerySectionTitle: "Golden Gallery",
    gallerySectionEyebrow: "TIMELESS BEAUTY",
    galleryQuote: "Where hearts align under golden grace, eternity begins.",
    dressCodeTitle: "Dress Code",
    dressCodeEyebrow: "ATTIRE & COLOR GUIDE",
    dressCodeSubtitle: "Golden champagne, royal ivory, or classic black-tie formal:",
    streamingTitle: "Live Broadcast",
    streamingEyebrow: "VIRTUAL CEREMONY",
    streamingSubtitle: "Witness our royal ceremony live from anywhere in the world:",
    giftSectionTitle: "Tribute of Love",
    giftSectionEyebrow: "WEDDING GIFT",
    giftSectionDesc: "Your gracious blessings honor us deeply. If you wish to convey a digital tribute:",
    turutMengundangTitle: "Warmly Invited By",
    turutMengundangEyebrow: "DISTINGUISHED FAMILIES",
    turutMengundangSubtitle: "With highest regards from both respected families:",
    wishesSectionTitle: "Warm Blessings",
    wishesSectionEyebrow: "WARM BLESSINGS",
    wishesSectionSub: "Inscribe Your Best Wishes for Our Lifetime",
    closingQuote: "Your esteemed presence and heartfelt wishes are our greatest blessing.",
    closingSub: "With heartfelt appreciation and honor.",
    rsvpTitle: "RSVP & Confirmation",
    rsvpBtnText: "Confirm RSVP",
    vendorTitle: "Distinguished Partners",
    vendorEyebrow: "WEDDING CREDITS",
    vendorSubtitle: "Our deepest gratitude to the distinguished vendors who brought perfection to this day.",
  },
  kalandra: {
    themeId: "kalandra",
    themeName: "Kalandra",
    series: "premium",
    defaultPalette: "champagne",
    openingQuote: "Two lives, two hearts, joined together in friendship, united forever in love.",
    openingQuoteRef: "THE WEDDING CELEBRATION",
    coverSubtitle: "Kehadiran Bapak/Ibu/Saudara/i merupakan kehormatan tak terhingga bagi keluarga besar kami.",
    openBtn: "Buka Undangan",
    quoteSectionTitle: "Janji Luhur",
    quoteSectionEyebrow: "ROYAL SOLEMNIZATION",
    openingGreeting: "",
    coverBadge: "THE WEDDING OF",
    coupleSectionEyebrow: "KEDUA MEMPELAI",
    coupleSectionTitle: "Kedua Mempelai",
    coupleSectionSub: "Bersatu dalam janji suci dan cinta abadi",
    eventsSectionTitle: "Rangkaian Acara",
    eventsSectionEyebrow: "AGENDA ACARA",
    eventsSectionSub: "Waktu & Tempat Akad Serta Resepsi",
    storySectionTitle: "Lembah Cinta",
    storySectionEyebrow: "OUR JOURNEY",
    gallerySectionTitle: "Potret Keabadian",
    gallerySectionEyebrow: "GALLERY OF LOVE",
    galleryQuote: "Kala dua takdir dipersatukan, keindahan cinta menjadi nyata selamanya.",
    dressCodeTitle: "Dress Code",
    dressCodeEyebrow: "PANDUAN BUSANA",
    dressCodeSubtitle: "Nuansa formal modern / Champagne Gold & Warm Tone:",
    streamingTitle: "Live Streaming",
    streamingEyebrow: "SIARAN LANGSUNG",
    streamingSubtitle: "Saksikan prosesi pernikahan kami secara daring melalui siaran langsung:",
    giftSectionTitle: "Tanda Kasih",
    giftSectionEyebrow: "WEDDING GIFT",
    giftSectionDesc: "Doa restu Anda adalah karunia yang sangat berarti. Bagi yang ingin memberikan tanda kasih secara cashless:",
    turutMengundangTitle: "Turut Mengundang",
    turutMengundangEyebrow: "KELUARGA BESAR",
    turutMengundangSubtitle: "Keluarga besar dari kedua mempelai yang turut berbahagia:",
    wishesSectionTitle: "Ucapan & Doa Restu",
    wishesSectionEyebrow: "DOA & HARAPAN",
    wishesSectionSub: "Sampaikan Doa Terbaik Anda Untuk Kedua Mempelai",
    closingQuote: "Doa tulus Anda adalah anugerah terindah yang senantiasa menguatkan bahtera rumah tangga kami.",
    closingSub: "Salam hormat dan terima kasih dari kami sekeluarga.",
    rsvpTitle: "Konfirmasi Kehadiran & Doa",
    rsvpBtnText: "Kirim Konfirmasi & Doa",
    vendorTitle: "Mitra Vendor",
    vendorEyebrow: "WEDDING CREDITS",
    vendorSubtitle: "Rasa terima kasih tak terhingga kepada seluruh vendor yang telah membantu menyempurnakan hari bahagia kami.",
  },
  valente: {
    themeId: "valente",
    themeName: "Valente",
    series: "premium",
    defaultPalette: "burgundy",
    openingQuote: "To love and to be loved is to feel the sun from both sides. We invite you to witness our eternal promise.",
    openingQuoteRef: "DAVID VISCOTT",
    coverSubtitle: "With joyful hearts, we request the pleasure of your company at our wedding.",
    openBtn: "Open Invitation",
    quoteSectionTitle: "The Solemn Vow",
    quoteSectionEyebrow: "FOREVER BOUND",
    openingGreeting: "With Joyful Hearts",
    coverBadge: "HOLY MATRIMONY & CELEBRATION",
    coupleSectionEyebrow: "THE COUPLE",
    coupleSectionTitle: "The Couple",
    coupleSectionSub: "United by destiny, inspired by devotion.",
    eventsSectionTitle: "The Occasion",
    eventsSectionEyebrow: "ORDER OF SERVICE",
    eventsSectionSub: "Order of Service & Reception",
    storySectionTitle: "Milestones",
    storySectionEyebrow: "MILESTONES OF LOVE",
    gallerySectionTitle: "Curated Moments",
    gallerySectionEyebrow: "EXCLUSIVE FRAMES",
    galleryQuote: "In black and white or vibrant hues, love remains pure and true.",
    dressCodeTitle: "Dress Code",
    dressCodeEyebrow: "ELEGANCE GUIDE",
    dressCodeSubtitle: "Formal evening wear in burgundy, deep wine, or classic black:",
    streamingTitle: "Live Streaming",
    streamingEyebrow: "VIRTUAL CEREMONY",
    streamingSubtitle: "Join our matrimonial service and celebration virtually via livestream:",
    giftSectionTitle: "Wedding Registry",
    giftSectionEyebrow: "GRACIOUS TOKEN",
    giftSectionDesc: "Your presence is our supreme delight. For guests desiring to send a cashless gift:",
    turutMengundangTitle: "Warmly Invited By",
    turutMengundangEyebrow: "BOTH FAMILIES",
    turutMengundangSubtitle: "Joined in celebration with our beloved families and kin:",
    wishesSectionTitle: "Words of Blessing",
    wishesSectionEyebrow: "WORDS OF BLESSING",
    wishesSectionSub: "Leave Your Blessing for the Bride & Groom",
    closingQuote: "Our celebration is made truly whole by your presence, love, and prayers.",
    closingSub: "With profound gratitude, the families.",
    rsvpTitle: "RSVP & Attendance",
    rsvpBtnText: "Send RSVP & Wishes",
    vendorTitle: "Creative Partners",
    vendorEyebrow: "WEDDING CREDITS",
    vendorSubtitle: "Our warmest gratitude to the exceptional creative team and vendors.",
  },
};

/**
 * Default Category Archetypes for newly added themes
 */
export const DEFAULT_TRADITIONAL_BLUEPRINT: ThemeBlueprint = {
  themeId: "generic_traditional",
  themeName: "Traditional Heritage",
  series: "traditional",
  defaultMusicUrl: "/music/bermuara.mp3",
  openingQuote: "Dan di antara tanda-tanda (kebesaran)-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya, dan Dia menjadikan di antaramu rasa kasih dan sayang.",
  openingQuoteRef: "QS. AR-RUM : 21",
  coverSubtitle: "Tanpa mengurangi rasa hormat, kami mengundang Anda untuk menghadiri acara pernikahan kami.",
  openBtn: "Buka Undangan",
  quoteSectionTitle: "Untaian Doa",
  quoteSectionEyebrow: "WALIMATUL 'URS",
  openingGreeting: "﷽",
  coverBadge: "THE WEDDING OF",
  coupleSectionTitle: "Mempelai",
  coupleSectionSub: "Dengan penuh rasa syukur dan sukacita, kami mengundang Anda untuk merayakan persatuan cinta kami.",
  eventsSectionTitle: "Rangkaian Acara",
  eventsSectionSub: "Waktu & Tempat Pelaksanaan",
  storySectionTitle: "Kisah Cinta",
  storySectionEyebrow: "Our Journey",
  gallerySectionTitle: "Galeri Momen",
  gallerySectionEyebrow: "Gallery",
  galleryQuote: "Cinta sejati adalah ketika dua insan saling memuliakan dalam ketaatan dan keikhlasan.",
  dressCodeTitle: "Dress Code",
  dressCodeEyebrow: "Attire Guide",
  dressCodeSubtitle: "Kami mengundang tamu undangan untuk mengenakan palet warna berikut:",
  streamingTitle: "Live Streaming",
  streamingEyebrow: "Virtual Ceremony",
  streamingSubtitle: "Bagi keluarga & sahabat yang menyaksikan dari jauh, bergabunglah melalui siaran daring:",
  giftSectionTitle: "Tanda Kasih",
  giftSectionEyebrow: "WEDDING GIFT",
  giftSectionDesc: "Doa restu Anda merupakan karunia yang sangat berarti bagi kami. Dan jika memberi adalah ungkapan tanda kasih Anda, Anda dapat memberi kado secara digital:",
  turutMengundangTitle: "Turut Mengundang",
  turutMengundangEyebrow: "Keluarga Besar",
  turutMengundangSubtitle: "Keluarga Besar & Kerabat yang turut berbahagia:",
  wishesSectionTitle: "Ucapan & Doa Restu",
  wishesSectionSub: "Kirimkan Pesan Manis Untuk Mempelai",
  closingQuote: "Merupakan suatu kehormatan dan kebahagiaan bagi kami apabila Anda berkenan hadir dan memberikan doa restu.",
  closingSub: "Salam hangat dari keluarga besar kedua mempelai.",
  rsvpTitle: "Konfirmasi Kehadiran & Doa",
  rsvpBtnText: "Kirim Konfirmasi & Doa",
  vendorTitle: "Mitra Vendor",
  vendorEyebrow: "WEDDING CREDITS",
  vendorSubtitle: "Terima kasih kepada seluruh mitra dan vendor yang turut menyempurnakan hari bahagia kami.",
};

export const DEFAULT_MODERN_BLUEPRINT: ThemeBlueprint = {
  themeId: "generic_modern",
  themeName: "Modern Minimalist",
  series: "modern",
  defaultMusicUrl: "/music/canon-in-d.ogg",
  openingQuote: "Two souls with but a single thought, two hearts that beat as one. In the presence of God and our beloved families, we unite our lives in love.",
  openingQuoteRef: "CELEBRATION OF LOVE",
  coverSubtitle: "Together with their families, invite you to celebrate the joyous union of their marriage.",
  openBtn: "Open Invitation",
  quoteSectionTitle: "The Union",
  quoteSectionEyebrow: "TWO HEARTS AS ONE",
  openingGreeting: "",
  coverBadge: "THE WEDDING OF",
  coupleSectionTitle: "The Happy Couple",
  coupleSectionSub: "Together with joyful hearts, we invite you to share this sacred beginning with us.",
  eventsSectionTitle: "The Itinerary",
  eventsSectionSub: "Ceremony & Celebration Schedule",
  storySectionTitle: "Love Story",
  storySectionEyebrow: "Our Journey",
  gallerySectionTitle: "Our Moments",
  gallerySectionEyebrow: "Captured Memories",
  galleryQuote: "Every moment together is another piece of our eternal story.",
  dressCodeTitle: "Dress Code",
  dressCodeEyebrow: "Attire Guide",
  dressCodeSubtitle: "We invite our lovely guests to dress in our curated palette:",
  streamingTitle: "Live Streaming",
  streamingEyebrow: "Virtual Ceremony",
  streamingSubtitle: "For beloved family and friends celebrating with us from afar, please join our virtual stream:",
  giftSectionTitle: "Wedding Gift",
  giftSectionEyebrow: "Token of Love",
  giftSectionDesc: "Your warm presence and prayers are the greatest gift. If you wish to send a token of love, digital registry details are below:",
  turutMengundangTitle: "Turut Mengundang",
  turutMengundangEyebrow: "Warm Regards",
  turutMengundangSubtitle: "Beloved families & friends honoring this celebration:",
  wishesSectionTitle: "Wishes & Prayers",
  wishesSectionSub: "Leave a Heartfelt Message for the Bride & Groom",
  closingQuote: "Thank you for being an essential part of our journey and sharing in the joy of our wedding day.",
  closingSub: "Warmest love, the bride & groom and our families.",
  rsvpTitle: "RSVP & Confirmation",
  rsvpBtnText: "Confirm Attendance",
  vendorTitle: "Wedding Vendors",
  vendorEyebrow: "SPECIAL THANKS",
  vendorSubtitle: "Heartfelt gratitude to our exceptional vendors who made our dream wedding come to life.",
};

export const DEFAULT_PREMIUM_BLUEPRINT: ThemeBlueprint = {
  themeId: "generic_premium",
  themeName: "Premium Exclusive",
  series: "premium",
  defaultMusicUrl: "/music/canon-in-d.ogg",
  openingQuote: "True love is timeless, noble, and crowned with devotion. We request the honor of your distinguished presence as we begin our lifelong commitment.",
  openingQuoteRef: "SACRED VOWS & BLESSINGS",
  coverSubtitle: "An exclusive invitation to celebrate the eternal union of two souls.",
  openBtn: "Enter Celebration",
  quoteSectionTitle: "The Heritage",
  quoteSectionEyebrow: "MASTERPIECE OF HEARTS",
  openingGreeting: "",
  coverBadge: "THE WEDDING OF",
  coupleSectionTitle: "The Couple",
  coupleSectionSub: "Handcrafted love, timeless elegance.",
  eventsSectionTitle: "The Solemnity",
  eventsSectionSub: "Times & Prestigious Venue",
  storySectionTitle: "The Tapestry",
  storySectionEyebrow: "CHRONICLES OF LOVE",
  gallerySectionTitle: "The Exhibition",
  gallerySectionEyebrow: "CURATED FRAMES",
  galleryQuote: "Where hearts align under grace, eternity begins.",
  dressCodeTitle: "Dress Code",
  dressCodeEyebrow: "Attire Guide",
  dressCodeSubtitle: "Formal & distinguished attire harmonizing with our celebration:",
  streamingTitle: "Live Streaming",
  streamingEyebrow: "Virtual Attendance",
  streamingSubtitle: "For esteemed family and guests attending virtually, join our exclusive broadcast:",
  giftSectionTitle: "Wedding Registry",
  giftSectionEyebrow: "TOKEN OF RESPECT",
  giftSectionDesc: "Your blessings and presence are our highest honor. For digital tribute and wedding gifts:",
  turutMengundangTitle: "Turut Mengundang",
  turutMengundangEyebrow: "Hormat Kami",
  turutMengundangSubtitle: "Keluarga Besar & Rekan Kehormatan:",
  wishesSectionTitle: "Expressions of Grace",
  wishesSectionSub: "Inscribe Your Best Wishes for Our Lifetime",
  closingQuote: "We extend our deepest gratitude for your blessings and distinguished presence.",
  closingSub: "Respectfully, the bride, the groom & families.",
  rsvpTitle: "RSVP & Attendance",
  rsvpBtnText: "Submit RSVP",
  vendorTitle: "Distinguished Vendors",
  vendorEyebrow: "CURATED CREDITS",
  vendorSubtitle: "Our deepest gratitude to the master artisans and distinguished partners behind this celebration.",
};

/**
 * Fallback generic blueprint in case an unlisted themeId is queried.
 */
export const DEFAULT_GENERIC_BLUEPRINT: ThemeBlueprint = DEFAULT_TRADITIONAL_BLUEPRINT;

/**
 * Resolves a ThemeBlueprint for a specific themeId, gracefully overlaying any
 * admin customized settings (e.g. from theme_demo_[themeId] in AdminSetting).
 * Automatically synthesizes a theme-specific archetype if an unlisted theme is queried.
 */
export function getThemeBlueprint(
  themeId: string,
  customData?: any
): ThemeBlueprint {
  const cleanId = (themeId || "").toLowerCase().trim();
  const specificBlueprint = THEME_BLUEPRINTS[cleanId];

  let base: ThemeBlueprint;
  if (specificBlueprint) {
    base = specificBlueprint;
  } else {
    // Dynamic archetype synthesis for newly added themes
    const rawSeries = (
      customData?.series ||
      customData?.category ||
      (cleanId.includes("modern") ? "modern" : "") ||
      (cleanId.includes("premium") ? "premium" : "") ||
      "traditional"
    ).toLowerCase();

    const derivedName = customData?.themeName || (cleanId ? cleanId.charAt(0).toUpperCase() + cleanId.slice(1) : "Luxenary Theme");

    if (rawSeries.includes("modern")) {
      base = {
        ...DEFAULT_MODERN_BLUEPRINT,
        themeId: cleanId || "modern",
        themeName: derivedName,
      };
    } else if (rawSeries.includes("premium")) {
      base = {
        ...DEFAULT_PREMIUM_BLUEPRINT,
        themeId: cleanId || "premium",
        themeName: derivedName,
      };
    } else {
      base = {
        ...DEFAULT_TRADITIONAL_BLUEPRINT,
        themeId: cleanId || "traditional",
        themeName: derivedName,
      };
    }
  }

  const seriesMusic = (base.series === "traditional") ? "/music/bermuara.mp3" : "/music/canon-in-d.ogg";
  const defaultMusic = base.defaultMusicUrl || seriesMusic;

  if (!customData || typeof customData !== "object") {
    return { ...base, defaultMusicUrl: defaultMusic };
  }

  const customLabels = customData.customLabels || {};

  return {
    ...base,
    defaultPalette: customData.defaultPalette ?? customData.colorPalette ?? base.defaultPalette,
    defaultMusicUrl: customData.defaultMusicUrl ?? customData.audioUrl ?? defaultMusic,
    openingQuote: customData.openingQuote ?? customLabels.openingQuote ?? base.openingQuote,
    openingQuoteRef: customData.openingQuoteRef ?? customLabels.openingQuoteRef ?? base.openingQuoteRef,
    coverSubtitle: customLabels.coverSubtitle ?? customData.coverSubtitle ?? base.coverSubtitle,
    openBtn: customLabels.openBtn ?? customData.openBtn ?? base.openBtn,
    openingGreeting: customLabels.openingGreeting !== undefined ? customLabels.openingGreeting : (customData.openingGreeting ?? base.openingGreeting),
    coverBadge: customLabels.coverBadge !== undefined ? customLabels.coverBadge : (customData.coverBadge ?? base.coverBadge),
    quoteSectionTitle: customLabels.quoteTitle ?? customLabels.quoteSectionTitle ?? base.quoteSectionTitle,
    quoteSectionEyebrow: customLabels.quoteEyebrow ?? customLabels.quoteSectionEyebrow ?? base.quoteSectionEyebrow,
    coupleSectionEyebrow: customLabels.coupleEyebrow ?? customLabels.coupleSectionEyebrow ?? base.coupleSectionEyebrow ?? "THE COUPLE",
    coupleSectionTitle: customLabels.coupleTitle ?? customLabels.coupleSectionTitle ?? base.coupleSectionTitle,
    coupleSectionSub: customLabels.coupleSub ?? customLabels.coupleSectionSub ?? base.coupleSectionSub,
    eventsSectionTitle: customLabels.eventsTitle ?? customLabels.eventsSectionTitle ?? base.eventsSectionTitle,
    eventsSectionEyebrow: customLabels.eventsEyebrow ?? customLabels.eventsSectionEyebrow ?? base.eventsSectionEyebrow ?? "AGENDA ACARA",
    eventsSectionSub: customLabels.eventsSub ?? customLabels.eventsSectionSub ?? base.eventsSectionSub,
    storySectionTitle: customLabels.storyTitle ?? customLabels.storySectionTitle ?? base.storySectionTitle,
    storySectionEyebrow: customLabels.storyEyebrow ?? customLabels.storySectionEyebrow ?? base.storySectionEyebrow ?? "Our Journey",
    gallerySectionTitle: customLabels.galleryTitle ?? customLabels.gallerySectionTitle ?? base.gallerySectionTitle,
    gallerySectionEyebrow: customLabels.galleryEyebrow ?? customLabels.gallerySectionEyebrow ?? base.gallerySectionEyebrow,
    galleryQuote: customLabels.galleryQuote ?? base.galleryQuote,
    dressCodeTitle: customLabels.dressCodeTitle ?? base.dressCodeTitle ?? "Dress Code",
    dressCodeEyebrow: customLabels.dressCodeEyebrow ?? base.dressCodeEyebrow ?? "A Guide To",
    dressCodeSubtitle: customLabels.dressCodeSubtitle ?? base.dressCodeSubtitle ?? "Kami mengundang tamu undangan untuk mengenakan palet warna berikut:",
    streamingTitle: customLabels.streamingTitle ?? base.streamingTitle ?? "Live Streaming",
    streamingEyebrow: customLabels.streamingEyebrow ?? base.streamingEyebrow ?? "Virtual Ceremony",
    streamingSubtitle: customLabels.streamingSubtitle ?? base.streamingSubtitle ?? "Bagi keluarga & sahabat yang menyaksikan dari jauh, bergabunglah melalui siaran daring:",
    giftSectionTitle: customLabels.giftTitle ?? customLabels.giftSectionTitle ?? base.giftSectionTitle,
    giftSectionEyebrow: customLabels.giftEyebrow ?? customLabels.giftSectionEyebrow ?? base.giftSectionEyebrow,
    giftSectionDesc: customLabels.giftDesc ?? base.giftSectionDesc,
    turutMengundangTitle: customLabels.turutMengundangTitle ?? base.turutMengundangTitle ?? "Turut Mengundang",
    turutMengundangEyebrow: customLabels.turutMengundangEyebrow ?? base.turutMengundangEyebrow ?? "Keluarga Besar",
    turutMengundangSubtitle: customLabels.turutMengundangSubtitle ?? base.turutMengundangSubtitle ?? "Keluarga Besar & Kerabat yang turut berbahagia:",
    wishesSectionTitle: customLabels.wishesTitle ?? customLabels.wishesSectionTitle ?? base.wishesSectionTitle,
    wishesSectionEyebrow: customLabels.wishesEyebrow ?? customLabels.wishesSectionEyebrow ?? base.wishesSectionEyebrow ?? "WISHES & RSVP",
    wishesSectionSub: customLabels.wishesSub ?? base.wishesSectionSub,
    closingQuote: customData.closingQuote ?? customLabels.closingQuote ?? base.closingQuote,
    closingSub: customData.closingSub ?? customLabels.closingSub ?? base.closingSub,
    rsvpTitle: customLabels.rsvpTitle ?? base.rsvpTitle,
    rsvpBtnText: customLabels.rsvpBtnText ?? base.rsvpBtnText ?? "Kirim Konfirmasi & Doa",
    vendorTitle: customLabels.vendorTitle ?? base.vendorTitle,
    vendorEyebrow: customLabels.vendorEyebrow ?? base.vendorEyebrow,
    vendorSubtitle: customLabels.vendorSubtitle ?? base.vendorSubtitle,
  };
}
